// AUTO-GENERATED by scripts/update-news.mjs via .github/workflows/update-news.yml
// Do not edit by hand — changes will be overwritten on the next scheduled run.
const newsData = {
  "updatedAt": "2026-09-05T20:04:57.129Z",
  "uk": [
    {
      "title": "Bangkok Is a City Full of Ghosts",
      "source": "Frieze",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Frieze.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMickFVX3lxTE1Dc3dramk2UlpuVVFjWU05TDdfYnpEVjNrQmZ0OXhUSFFtb0hvMWF5WlhpWVZXSTYwWE1GOXFzSklhUmFNMzR2RHFVTk5rcjE5WThGYzB0QmJfcmdpVmJzUzhOcGhvd3h6bUIzTncxcjI4dw?oc=5"
    },
    {
      "title": "Weekend reads: The AI ghosts ‘contaminating’ academic publishing; court upholds whistleblower suits; Ariely paper retracted after sleuths flag tampering",
      "source": "Retraction Watch",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Retraction Watch.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilgJBVV95cUxQYl9hbXhrOGQ4LTMzektHUGotemtqUmQ1OS1GNVZZQWRaNXFMSDZjakhtRHJ4eE9Kei0zakpNNjhDc1F3UWM3UlpJdjFIMVRvT1cyelM2aVNMX3NTaDFqVE43dWtTUVJpcTVIS2dPdWtYQnI2Q28yN0p5TWl6bnJRT3cxVFR1V2g1UWZTbUd3djVGb2JyeDdseGZzaS1yWUpXVl83QmhWYmN2TUhkUVRuZVNzS000cE5YMDN0RjBDUGZTeTNpa0tzVUNfY2lJWG9uNEp3a084dVhzS282Q2lCZTZPYksteU1SSkpXSHU2dVhfZ0JoRTV2WS1IUzY1NC1nSWQwZHN1WnFuYzFzZ2VWTjhLT05FUQ?oc=5"
    },
    {
      "title": "Is There Alien Debris on the Moon? Some Scientists Plan to Find Out.",
      "source": "The New York Times",
      "date": "2026-09-05",
      "excerpt": "Read the full story from The New York Times.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxOd2NEVGw3ZDFNSTNVcTB1RU1yQzl4OGN4bkV3NGo3Y3JHY2ZLNU9tUzZFVVdENldnVDJZOVNReHNHMHhZalpPelZ1d0lEaW5hWEZac2MwRXdWOXpTaVBCWUhoU1pBTW1kbjN2TUNDZWpXQXJKaTdMSnpZN1VIejl1OW1zWGV0bTlzUWFyOENoNGhkSlBRd3pLU0ROR21tTU1UckQ1M3ZNR05pVTE5MnFvMUREMlhrQmRFUWZnYg?oc=5"
    },
    {
      "title": "The living care for ancestors and wandering spirits at Malaysia's Hungry Ghost Festival",
      "source": "TelegraphHerald.com",
      "date": "2026-09-05",
      "excerpt": "Read the full story from TelegraphHerald.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxPTXBNc2Z2VmFQTXVoc0RaM0N3M3lDS1FNNUpncGVtNU91Z3hkek1VRXAyWS1OdC1ZRmNwSDRuSW92c0E2NTVyYm9OSVZTMWdaQ2RiRjJ4R0h4T2tRZTBXQ0tEZDluUURVdmlPamE2TWt5MlctMktpZy1aMXpIdUhiLXJlUm13Tkg1blp5empmTlJ1a3NqeUdCM0U2aw?oc=5"
    },
    {
      "title": "Town Staff Suggests Alternate Placement for Route 62 ‘Ghost Bike’ Memorial",
      "source": "The Bedford Citizen",
      "date": "2026-09-04",
      "excerpt": "Read the full story from The Bedford Citizen.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxOY29kWmFEalRyYTVuQkFlN2RQRUJIN1F1aFRqQjIxVmdQRHhiTnkwdnI3S3lHMUNrVThRNklpYy03X3lIQ1cyNmZBcFpSVjAzNzZ0TFlUYlV4X1B1OC1tYWpVTTV0RU41UXJvci1sc1ZhWWQ0Q0h0LXlCbnM0SFpzNEJWdVJqYV9XZGp1cU5IdXR0Rzl5OFV2X0F5WVZkcFB4R1BjcmVZb3NnRzUyV1lsZg?oc=5"
    },
    {
      "title": "Saratoga Springs History Museum Announces the Return of Halloween Ghost Tours of the Canfield Casino",
      "source": "Visit New York State",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Visit New York State.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxQeGF6Y1R6SXltNlI5a1dJcU1WTjdNb05fZVl4RmFtSXdpUHY2a05Ma0Q3cjV6RUZ5YUVmMzBYOU92cHFCVFVlVUN1eUdubWxEbi1Wd1MwRV94S1JPaGtqZE95MlFLbE8yWjY2V0lvN1lUSVV5VHg4QkIyUmNmdHZXb1R4WFhyM1Y4ck9VOVFkb3djNzFyYWNHSllqeU9JX09mMWN3RkxIcmotNEt6Rk1UNEgtN0h2SGQxSl93V2VXdFN5NVBWanA0U0ZqWGFHUEV0bm9iVw?oc=5"
    },
    {
      "title": "Niece of N.H. couple famous for alien abduction story to speak at Exeter UFO Festival",
      "source": "bostonglobe.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from bostonglobe.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxNRzVuSGlWTXZjam1uenV1VXNYbUZXV1hGUDlBQkEwcVVoNjlMNG9TcFVRZ1N4QThCLUI0MGF1QW9CTDhIYXlNZ0MxNnBVOHV3YmdJZS13UTA1MnZRNTdVcDMtSENpUmIzNEVnVHZWRDZZREhmZHM3aDgwUWF3R1M4bXlkRUhESThBdHJOOA?oc=5"
    },
    {
      "title": "Book Review: ‘The Ghost of the Mountains,’ by Kulbhushansingh Suryawanshi",
      "source": "The New York Times",
      "date": "2026-09-04",
      "excerpt": "Read the full story from The New York Times.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNYnNrNFhwMVp1Y1hwTU1MUjE5bUVYaG9vdHFtZ2lrWVdwVVRHUjRvSGdiR25HQkltbjdWdmNKZWo2RTNocmZyNi1SaS1IRmhrSFlLOGtDWVcyMEk3b3VYc09sQWJCWXZRM3RlU1ZUQ1dkRjZCSDVjS2x0aHFIR3U1T2lmQ21mYUlMNGN3ZEZidUNPaDRGVXlVb3RIOXBVYnJnUW13NDJZc2FNczg?oc=5"
    },
    {
      "title": "Gainesville residents protest order requiring GPD officers to report suspected ‘unauthorized aliens’",
      "source": "WUFT",
      "date": "2026-09-04",
      "excerpt": "Read the full story from WUFT.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi2gFBVV95cUxPV2hObWw1ajNOQmtnOF9YTzVielJxUDB2UnF0MUJKbVctQkMweVY2OU1VZTRueXh2Y003R0FYY3RSN3puYW5WYXZuSFdXdlM4Wm0tSmxQUnpQVEZ1RzVqRmxGaS03Q2pvRDNYTVlzMXhUbk9CUmNFeUlUbmYwTndFWVVVaEUzMDZCdEhfMUdwd0NUMUpyUDQzNE1XenF5YjU5bGRucU9OMTcxNzBXS3NoaXNUVmtITGp4TWlRZkEtUm01SmNzelVLdDN6dEZ3T3MxZmExTXhzWHFKdw?oc=5"
    },
    {
      "title": "The ghost penalty run-up: Why did Youri Tielemans mimic Bruno Fernandes?",
      "source": "The New York Times",
      "date": "2026-09-04",
      "excerpt": "Read the full story from The New York Times.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxOcmZOcThFeG9LaTl6QUFFS3VxazhobEZCTllvVGxBR0o5MHpOdExRd3JXcWNJWFdOVmQxSDBXa0t5bG5uTTVkdXlGRjVZbVZIOUhUY2hDX1hoU0ZRSFplYU9kVWwwcExIMW9wY1pjbGhKaHFOYlp6OW1xeHJUQmJRWl9KVlNxM1phZVpOYjlEVzRBaGRCU0EzeDFGeUo1YnlWcWRmOFAybksyYXR3cEQ3TS0xM2NfUkpXejlfaE5Va00?oc=5"
    },
    {
      "title": "No date for long-delayed £40m 'ghost junction'",
      "source": "BBC",
      "date": "2026-09-03",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiXEFVX3lxTE0yYTNfSVczU1ZXeGd0V1lHU1pNZXkzWXEtd3JjNUxxbEZKYXJQeXFZb0hKd0g4Wm5PNTN2YWNsdGdBM0tiQW5IY3Zxdmt2TV9henp1Y0dSMEpNcHEx?oc=5"
    },
    {
      "title": "Pentagon seeks access to vast private UFO records collection",
      "source": "defensescoop.com",
      "date": "2026-09-02",
      "excerpt": "Read the full story from defensescoop.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxQS2lCbzZkQ1dobGtWVkFsYUQ5cmp4MDBzZDFjTlhpQ1hOWlVKTVBEY25aVWQxWTFUN2E0R2lyeTdyVlhoc3FqalFnT0pUUldlWXE4RWdnRUJTak1CR2VTUDdQTzFrS0tLazJIekpnb1dNMXpnTzR3SFFrUy1xN3ZKVEtTcFZMYjVCVjZxTUJvalN0ZlRhNXZoQ2h5ME1qQQ?oc=5"
    },
    {
      "title": "Man in Bigfoot costume prompts high number of calls to police in coastal Maine town",
      "source": "bostonglobe.com",
      "date": "2026-09-02",
      "excerpt": "Read the full story from bostonglobe.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMie0FVX3lxTE1MTVFuSXlON1ZmdjZoSW53dGRqM1pzZ3QyUW9sSC1EOWg4ZzJjXzlJZ2daazI2V2tqQjJxb2JhY080eTN2N1IxNUdFaDZIcldwSEtpckZiRDRtaWJzTjNqcjB2YU5lRFBCSGprSFVBWlZiN2VHd2lCMm5EYw?oc=5"
    },
    {
      "title": "Scientists discover bizarre 'Alien' microbe that gives birth by bursting open",
      "source": "Heriot-Watt University",
      "date": "2026-09-02",
      "excerpt": "Read the full story from Heriot-Watt University.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxOcWZDQmVHcWxWSy14UTJxNi1VNnhkaENuMENiMlRYUmRZTVk5dUJJY0NqQ25CaEdPYzQyOXUzT1ZvZW5CejlHOERMOTByRHpqeGZ0Q2dqV3BDaG1XVWRPNjBXeXFZT25JbEJwS0RhcXpLd3VwRDhfa203bVgzVmFVZzNqNmtHSkpmNlhRcWJNdWduMkdFcUpSVmI5eVFmb2l3UlBNTVJWY3VDUQ?oc=5"
    },
    {
      "title": "Bear McCreary on the Lessons Learned from the Akira and Ghost in the Shell OSTs",
      "source": "Crunchyroll",
      "date": "2026-08-29",
      "excerpt": "Read the full story from Crunchyroll.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMigwFBVV95cUxNRU1MaWpzVEY0TVpyMm5uaGNNYU1pcW15c1daN1BOVGt3aFZsSHczRnhoN3Y5cTRCY3RDMHVYQ3hlaWZDbEFDUVRzRVMzMldTSWx1bjJJNFI3RS1TdExBNl85T3hfTHlOTGFNQmhnc0VTZkp2WThya2o0akotTFhoa3M0VQ?oc=5"
    },
    {
      "title": "Americans Still Skeptical That UFOs Are Aliens",
      "source": "Gallup News",
      "date": "2026-08-26",
      "excerpt": "Read the full story from Gallup News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMifEFVX3lxTE9adTF3MXJucngxM1p1dmdXNl9yVEhueEdoWjlMazd5NXpfS3ZyOGhaYi1pdlFmQUJsVlBGc3V6MWNaLU1IVV8xU0I4aUp5aGJTd2tGNEtXUVp1c0ZpeVFjT25HNjVxaFNHLTZBc2RNN3A1WWxMSzNJODhoOGc?oc=5"
    },
    {
      "title": "‘Ghost Job’ Ads Are Getting So Bad That Lawmakers Want to Ban Them",
      "source": "WSJ",
      "date": "2026-08-21",
      "excerpt": "Read the full story from WSJ.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPSUR6MWdteWVfcHgwM0lTWTh1SHFFTTVmWkhqS0JpX0hmazJCYnQtSEw0Y1Y0WGdKTHhJOFVrbFpNN1U3Y2c1aXdtcG1uSy1abExtOGhHMTJfV1puRmtaZkYxQ3BocUtqc0dBZkY5WWZfQmswN3ljVl9mS1kyOVVIWmQ0Q1M1Z3hLVFJ0dERqemRtM0FHMVNxZ1Z1MjJxMTJqN1BjX2FoWDJzU1VWelNsRg?oc=5"
    },
    {
      "title": "The great silence: why haven’t we found any aliens yet?",
      "source": "The Guardian",
      "date": "2026-08-11",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxQN01nZWZBRE1NOEdrMGRkUDh3UkxQN0hDQmZkVnV6ODhsNFdVbGs5NHd5VjNIYndCWFUtUXlvaEJ3MF80SVhORi04dUlyUWp4bkJXbTVjWVlhN0s4VDNqX294NEF5OEF4QTE1Sm9XSEEyXzhpaXREUFR5SUd4bE8wbWw3RUR3MWdNejc0UFEyM0xlTFI3ZGpGMjg3Sm9sdw?oc=5"
    },
    {
      "title": "Rocket Lab Unveils GHOST Deployable Launch System to Enable Responsive Space Missions Worldwide",
      "source": "Rocket Lab",
      "date": "2026-08-10",
      "excerpt": "Unveils GHOST Deployable Launch System to Enable Responsive Space Missions Worldwide",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxPeks0el9WNzJZTm9uV1c1VFlkZ1Y4eUdYSnJ0YnRjUy1RT3VacDFIVWV4Z3JxQlRUNUdxdnRMVGhLZ0FzcGd2bXV5N2xQSnpIMzB5T3JSSHItT2l3aXk1VEpvMU9DSGhvRTJTVHNfTTd6aUZfZWJhTjl1TGxNZTRnUW90dEhaVWR1bEpEaUxMUjBUUS1tNVJLU1B3YURFNTgwdEUxTFBjYkpIZmRhUkJ6SXhTT2oyZXh5TEdJanFhTDRlNm5lTk10Um1B?oc=5"
    },
    {
      "title": "Pentagon releases fresh batch of UFO files",
      "source": "BBC",
      "date": "2026-08-07",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTFBGNjdZaXNSbFNGN1dHdk1tQkx0aXo5V0VEczJYSWxvT0ZQY2ZsRGdHZFU3dDhvekpnV1pPNlVIZWlWQ0RfVHN4aUh3a3V1SlEybFE0bHI1SXpJUQ?oc=5"
    },
    {
      "title": "Department of War Publishes Fifth Release of Unidentified Anomalous Phenomena Files on WAR.GOV/UFO",
      "source": "U.S. Department of War (.gov)",
      "date": "2026-08-07",
      "excerpt": "Read the full story from U.S. Department of War (.gov).",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxNaHJtX1ZyZFY5aXFyd29oeDBjY2xxbTVuaW4xeDU3cjZ3Ml9rY1c1cE5zQXJ2RFE0YTR6NjZRRHo1SmhCUHpFSUsxVG9zRlJzNUZpZGpFd0lMOExjUjJWN0E5OTYwa09XbVpaRHMyZXNLaWpad3VpMndsc2taVjdvTzVaX21kcG1ENHJvcnlJQXNmdXZWMTBmQkkxYk4tU2VpcWVuTDZ6eUFEOWdOUEU1N2kxRE90NEF0VlFCOHc0UkJoTTdfQ1JNbDNVUTUyemlvcHd4MA?oc=5"
    },
    {
      "title": "Watch: Pentagon releases fresh UFO videos in new document dump",
      "source": "BBC",
      "date": "2026-08-07",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiV0FVX3lxTFBYREVGSVMweGZIQTM1YXpYQ0ZjNkkwTjloMVB4M0NkN092d28yQnBCdHR2MlpfMVExZm5EYnd6cGxpWktjM28ySXRudnFjTTlhUjlnY2dOWQ?oc=5"
    },
    {
      "title": "Latest Pentagon UFO files release includes video of mysterious ‘cold orbs’",
      "source": "Scientific American",
      "date": "2026-08-07",
      "excerpt": "Read the full story from Scientific American.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxOdzJvODkzOE91X0VOOHZzdC1zcWdYemNzQmotZzZiQjlQRnNTbWt5VFRWdFI3eVo1NWZrTVdPeHM2NEJaTW0yNG51akhmMlQyVEpZUWh2TFFzV1lJa05xTDAyNTEzWENmeHdJcjdNUU1EOTF5UWlZTTd2WjFmT0N1YURfYm1mZEsyVV9BOExVWFZyaVl3YWpraTJfNkJjaHRoc2VlMG9pbngyWDlmMFA0T2pXUHZiWE0?oc=5"
    },
    {
      "title": "Video - DOW-UAP-PR38, Unresolved UAP Report, Middle East, 2013",
      "source": "DVIDS",
      "date": "2026-08-05",
      "excerpt": "Read the full story from DVIDS.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxON2E2bHJjYUpxTHJZbHhXMzZONXUwYkMxaWhldndEaTY3SW5nekU2bzEwamY2UXprdW1WTnZUSHlQei1QOEJiRHlha29xaTduV1FReHNNSDd2a2ZjenZJa2hHbDJpRmFXWEpJOGtTTkVoM0YtM2ZQa1RkeVlSOHhtclNmWWIzcHFMaDZlWFd3TjZ4VFVX?oc=5"
    }
  ],
  "europe": [
    {
      "title": "Pink Elephant hosts 4th Annual Route 66 UFO Festival",
      "source": "The Troy Times Tribune",
      "date": "2026-09-05",
      "excerpt": "Read the full story from The Troy Times Tribune.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxOcndZNkZ4TEN4ekRDeXY3cC1iMWpZXzNVcFlESXpabU15YWlGUDBMLVktM29ObWlNU0dhWGNSUVBaOFJCLVo2ZzdEOVRIUGpUSlBOZm5nNExjb0x0dERwSDhtMUI0WUFuR3JZNm80X29HUzFzclJXQkY1WGJzS1hWcXloU0dfTzRkR05rM2JfaGJEMjFhWEIwd1E3VEhWQQ?oc=5"
    },
    {
      "title": "15 Best TV Shows About Aliens",
      "source": "IMDb",
      "date": "2026-09-05",
      "excerpt": "Read the full story from IMDb.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiakFVX3lxTE8wUDlVZkczc2tkZk1aYVpzckJxYzhJWURjcURLX3RXVEh4UlNUNHpBX0FCUjdUcWwyR1RiOHNUdVhBUWNVMjR3M0lSNE5nRE1FaEtoM3NPbVoxOHFQbnAtWjBKZTFaeXAyMUE?oc=5"
    },
    {
      "title": "15 Best TV Shows About Aliens",
      "source": "TVLine",
      "date": "2026-09-05",
      "excerpt": "Read the full story from TVLine.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiakFVX3lxTFBaS2dsTWVsOVp1SktIUXF0OFI4WGJfRDlmQURFNVlZM0M5UHJRVXNxajJ1STVKY3Zxamh6Z2d1X0JhN2J5dm5lZFNlaVdyNHRJbjRmZjVsamIwakRrdlZHRG9xNngyRG5vT1E?oc=5"
    },
    {
      "title": "The Mystery of Youri Tielemans’s Ghost Penalty Run-Up for Man Utd Has Been Solved",
      "source": "Sports Illustrated",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Sports Illustrated.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxNcjlDaFRKdE1NVV9fRE45blVJYmxiRmRvandoQW83QWJoMUEtTlBnS0E3eUJmcmJsd2NBVmJVckRhLTdaTmpKczRtaXFuZUhQOWxZeFRMaXNJRFBEVVVvcWNRNFlrSW9pM21feFlVdmtJQnBUSHpVX3Yxc0dyNjlTVmU0eHZieFlXWHlqQUtB?oc=5"
    },
    {
      "title": "Comic Book Preview – Star Trek: Red Shirts – Ghost of the 21st Century #2",
      "source": "Flickering Myth",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Flickering Myth.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxOa21hSnFhaFhOVE5rMHFBY3RLUGZsMTk4TFJ1N2NxUDZFcVEzLXgtWkVQS1ROU3plV2oxZ0xjeXNPbWxyLUFBYVU3YzBFcXBoeWhCcEthUGdBRGl0SXZPYURVY0NmaDZWNGF0OHZTcmdSWEpTb1RuTXFWUE9mSDFzQnVwQUhTWXA5anRVRVI5OTlFenllX08zcXFyczZNQy1E?oc=5"
    },
    {
      "title": "Ghost Face Vodka Rolls Out New Flavor!",
      "source": "PopHorror",
      "date": "2026-09-05",
      "excerpt": "Read the full story from PopHorror.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMibEFVX3lxTE9fWFVKYThiak9TeVQxSW16TzdHbXljUDJhS3ZoS3J0dTduMXBpSEFlNlRZOVRVZkx6NnhpWmdNdUNYT29Iem9FNFZjVURuYThXZmY4RWp4RDc3UVZPZmp6QlFQTFNlamlhd29MVw?oc=5"
    },
    {
      "title": "\"I walked for hours through a unique desert landscape in northern Chile, where the rugged terrain traps sea mist in ravines,\" photographer's rare shot of \"the ghost of the desert\" honored with major wildlife award",
      "source": "Digital Camera World",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Digital Camera World.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMijgNBVV95cUxPU3MzYXBUM2JIR1VLcWN6VTI3Q0hQNFVlNWd2Q0JSU1U0NWNQVkNRTEZGWjdrVmp6TWIxSy1UbHVSb0RyTWNqR1V6ZE1EeVZ3ZXNvNmlhX011Vk5sa3BJc0E2VGFpX29HazhBZzY5d2lBaVUzdzlsTEN5QWlEM05UbmFoWktHbTFHbElfM0FuQlVuQjJWUHdLbEYwazBCTThySWNURDJud25EeG9meUJ2djN5SkhGZ2UyenJ5bnBPVnRxOUhyTGZDV0g1RUhhcHRUNDVlcUdTUFJXZFp0V19Qb0Vndi1EX0FBVTBrdGxWeVNwSDJqc2t6UWdmZEFybFU2Q0k1NHpYR0lnWmczOGF6R0lpQVZnV1N0Ym5zWERCelRmb0g5MDRsa1lRaF9oRTd5a0R0WHlWbGlLOUtfWGNUeUZNTWx5N181QnROWHFpaU9kMGtVLUdsX2V5YXhyZEV3cl9aMHF6blFqV2lZMW5Sel9Vb2Q3LUFzMEdPdHhpMmhvdG1oeGlNbExCQUU4Zw?oc=5"
    },
    {
      "title": "Book Scene: What might an alien encounter look like? Tyson turns to science",
      "source": "Yakima Herald-Republic",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Yakima Herald-Republic.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi-wFBVV95cUxOU0hjMjVNc2ZEcXFZa2hlX0kwU0U1RDRhMDVLa0xCaXNlOUtHaFZvLXFOUlFMMUtnME9sODU1QzVUM2s0R0xWQmxJajd5c1hXbzRxUjZOdVM0TllkYmhjRW92SUc2RmJzXzR2SnJZWUVneHZ0UGFlb3JrU1BuUDNuYy00V2k5emkxZGVXYkRoRGZUSFlBM2VOekU0SU93VzExdFBXYkFtanV5RkFxbXVPMFNqNGp3eTM3NGVLN2pOOXdPUTJjOU1LaXRNaUFyZ3JVR1Nna2oxVElYcVlwUkY1cE1BRnVKQVNHMFVhZGpSVWxoekJtcHlhWkhGZ9IBgAJBVV95cUxQU2xUN3hmS1RieHp3ckZzMnlfcWtQMUtjNS1Nb3RrdUVXYkRyNklBTllDaXlkMnRvOHhpV01qbzZUcm9LNnlYWkVaa2NMbF9SVnNHT29zVXV6eVVqWkFrWmo5czNqQlIwWWxyTGp6TlUyaGNkRHR6Ym5PeEYxYVhENDVuTXZlMGtPMFVrOV9Sb1N4LXJQWDFzeU1yNURTNi13TVNvWHNvVmJOT1dXZE5yY1lvR3VSdlFPU1ZsLUpZOVk3SjZEMVNnMWZpTm92U1JicEQwUHVKTHUzRlNBNDFvem56Y3NRd0gzMVJObUVha01LbVdHaks0NE1Oank0TFho?oc=5"
    },
    {
      "title": "Alien: Isolation 2's art director reveals how to make the game less scary",
      "source": "Gamereactor UK",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Gamereactor UK.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxQbkZ3LV93bGZJcHRBUXZRMk5qWHA3dDdiSTZEYVUzM3V3V1lJOUhYN2NFdy04ZVBabThrQ1JWT1ZkWWFHUU1jcTlWVHB6MEZ2QUxoaWEyNmNyeTRGc19BT0ZUd3FtQkQzcm9nUlRVbkNnU2pVVVQ3dkh2S3NMWU5aZkZ3Y2h0SU5VYlp6dkJrMGtzVVB3Z3VSOExFSVJ2MEJRb1phb2k5cXVPdFU?oc=5"
    },
    {
      "title": "The Frenchman trembles: the ghost of Ronaldo haunts Mbappe at Real Madrid",
      "source": "Goal.com",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Goal.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxQbVcydktiQVRmbzNvQmFxdjM0YXhDWVg5eGVsdUJrTjRYbWNhVjlGdjJETVBza09UOUNJZG5HRmdDZnZNbkVwRXc3bXdDMG5NTVpud3pLbm0yYUU5VDZieks0VUkyc19oYjFIcTliMnJ5dE9OTW44MUQ2dGFUZlRjalpwMG1VU3NJTk9VclFLbHYxZm9pUDEta3hVWE9EUHZoeVk3WFh1M3ZMVzB3WWloVVNnYVF4bUJHTmZSdF9n?oc=5"
    },
    {
      "title": "A New Observatory Concept for Imaging UAP Orbs",
      "source": "Avi Loeb – Medium",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Avi Loeb – Medium.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMikAFBVV95cUxQQkQ5N3BLcmEzakN0OElGMjZoYlVPMm51UjBwQnJNZmkzMG44R3hmUzU5OWFvVUppZk9JMG56aHpBemNDVjdpTlpwMVVKYWhVR3lEc250NVlNSUVkblh3R09GX3JYVUNsNjlsUFI5V0dKbVpYZk4tZmFrSWdXQ3duQU1VcW0tVXpZTUtTV21IT08?oc=5"
    },
    {
      "title": "Ford, Nicholson, Beatty: every star who turned down Ghost, and the $500M they missed",
      "source": "3DVF",
      "date": "2026-09-05",
      "excerpt": "Read the full story from 3DVF.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxQN0lGR3F6bEVjUkU1aVNXOEtkZ2FpYUhScVNFaWFWanYyOGZkeEY2X0pvTlFWRzUzam90cVVZSnk3MUdSUXBhTE9ZWEIySEdCNVVvWVZKV3RjS1RQQVZKQ3J2YWl3WTNmZkEzbFhDbmFUZkdyNkJTYjNYZjJFS0hWZnJ1d1RLUXczRFdFa0ZJc2hIdk5NcUdOYXFDZ1daR3JYb2c?oc=5"
    },
    {
      "title": "J.A. McNally Invites Young Readers Into a World of Ghostly Mysteries in Zackery the Teenage Ghost Hunter",
      "source": "24-7PressRelease.com",
      "date": "2026-09-05",
      "excerpt": "Read the full story from 24-7PressRelease.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi7AFBVV95cUxNdkVVdmV3bWF6M1BfeWFwOVRFdjlVY3IwUHlXbDdsRVBfbW1FT3lrSUFHb24zRFRtUk8yaDNITmdNYXpyTlUyTTVZOHQ4bnZXalRKVmpaa2JjeVIxNlYyeE5WZEpXNG45QTlPTEhZNm1YSnhEYmM3VjRiSFRna2Z4bjRZdkFjeklwX3AydklFaXkwWVd1SnZuc21aeFgxZzlQZFVjUlYwODdwN3lUUnZCVG5oRzZHQm9Ba1hsZkNfeUwyODBtbHlEQ05jMmJIYWZYNWZNUFNFdmVGdmtnMGFmd19oTlRmSjFLd0VkMw?oc=5"
    },
    {
      "title": "We’ll soon see the flash when two alien planets collide – and it'll dramatically transform our understanding of the Universe",
      "source": "BBC Sky at Night Magazine",
      "date": "2026-09-05",
      "excerpt": "Read the full story from BBC Sky at Night Magazine.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMibEFVX3lxTE4xWVRDN1dqU2c2Z1J0UVpZVFFTazdFQzM4d3JTUHlYSkp4ZGpXdUx2OU92b2E3RDhvY3luMEgxczBSSUJhQkdOLVVKRnpmLWFNXzEyRTliTUV0TklDcEt3V3pqMXRIWWU0UUdKdQ?oc=5"
    },
    {
      "title": "In the video: 2026 Isak mirrors the ghost of 2025!",
      "source": "Goal.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Goal.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxQOUJ1UXd0OHBoQ1NQR1NFdlVfZG1XanhHcUVOUDBpTFhyeHU4OEQtd25Qb3FyQ0Z6U1VQTFYyeGwxc3ctS3hrRXJXb2EtNnVENmEzQmlocTBKZEN2dDRRQ2NJUXFnaWlZVDZXVFRFZkxPYTM0dmd2LTU2clNnR3RvQlpPUHlBQmlZdVk3VF94R0ZZMlQzX0xrVQ?oc=5"
    },
    {
      "title": "Ghost point controversy can't stop Suncroft progressing past Confey in Kildare IFC",
      "source": "Kildare Now",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Kildare Now.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMixAFBVV95cUxOeUhEeERwVjA0clg0cUpKb29rQnFvX1MxTE9aTXFJclV5NGx4eS1EQzRiRUhmTk9xSVZUUm1xSC1SQ2o1dGpOR3ExLVpBdFg5UTYxZ0dIanlYdlZ2ZlRvNlNPbmNfcVcxSTZDSC1adHRuei1UX2hrdHVLMEdSYmhuWERYbFE0RVJaRGlQR3gxQTctckVXR1draXA2UV9QSDBWck9ZUVlscms3Wnh1dE5vRDc1Qmd2MDQ3bDZUQlRlbUMtTk9m?oc=5"
    },
    {
      "title": "“The biggest thing to happen since Christ”: Merle Haggard’s UFO obsession",
      "source": "Far Out Magazine",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Far Out Magazine.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiakFVX3lxTE4tbnFBdVllSDJVb2gydURDQmpoLVMyNlBWa1hJem5keGZ3aV9ZSVU5Z3hwSXQ5bEFfcTJLVTc0cTVpYS0wdlpfY2Rjb1U0Yy1mYkJ5VnVjdlNDZjQ0cXpaVjYxZVhic194Vmc?oc=5"
    },
    {
      "title": "Near-perfect returning sci-fi series Alien: Earth gets exciting filming update",
      "source": "Digital Spy",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Digital Spy.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxPeTlJYS1lN1JfOWJLWlBNaDU5aEZlMmZZWmpkeFJjMGxQUkQ2MWY1SjFUS1c5SW9uUHBOMmZjbGJRcEp5U05BNE1XMVFWRmVEeFVMTlA4N3luVUFoZk83X2pzbEFZQWdFcmVudWxzckoyM1FyZ0tVdVg1R01KTG1lX1dB?oc=5"
    },
    {
      "title": "Why Cate Blanchett Went All In on the Absurd, Sincere Alien Comedy ‘Alpha Gang’",
      "source": "The Hollywood Reporter",
      "date": "2026-09-04",
      "excerpt": "Read the full story from The Hollywood Reporter.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPaXZDek10dWdmY1NJSDhnN2RFOW81OVl0ejJNVG52MGlMUkpMWU1acUNSMkdrSXZUT1NPamw2VDFWdnpQZ0NzVWVFNTlIYzFieTJyU2hERE1FZXJzRFo4dXc2R1ZialhzeEUxelFic21mb3pMSGtlR08wdmVjRmlOQW1hakQ4R0x2blN6Vm5Kekh2Qm9yVEtHeUVtYXExekQ2c0F4M3hpX1F6WUJFMlI1Y29sNXE?oc=5"
    },
    {
      "title": "I Drank Fanta Ghost Face Soda",
      "source": "ScreenCrush",
      "date": "2026-09-04",
      "excerpt": "Read the full story from ScreenCrush.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiYkFVX3lxTE1KUTY2WG5Wa2xsNFA4VjJsb28zTmJBbHRpOGVReS1FTHpHbFFYQ3hMTVg3OENQRzB5R2loNlJDeFJJLURBWXlQckdYd1paTHNtdGpyU09xVjNjX1hITDhMXzRB?oc=5"
    },
    {
      "title": "Salmon mountain ghosts stalk a market awash with fish",
      "source": "intrafish.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from intrafish.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxNQVJBamQ4R2d2ajZFOHJXeWtZVVpGQlVNR3MyM1ZmLUhGNDIxczdaR1hvcHowSGV1S2dINlhrcV9pUXA3MmpYM2tHb1pyZkhpa0VlZGplNXBCT19qbmFvaVNkQXl5dGU4WHpQeEJGNnZZZTF5U3hFTjZUUUJhNDlvel9rUi1FTTMtMnJEbUNVcjBJWGZWVENQYzJ4NkxoMmc?oc=5"
    },
    {
      "title": "43rd Liberal Club Holy Ghost Feast set for Fall River",
      "source": "Fall River Herald News",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Fall River Herald News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxNY3Z4bnRDWFJndUpYcHgwRjZHb2dtN0NLcG5jTk5QSlZJX0FFZ3JfalNKRkRPZThCbXFBd3ljalBnNS14ZGdiTjd1SnJpVWkxUV9STW00QzRJV0lqRzgzMmFNbllqZDdxTXVFSGlURGpmejhZVHM0NkxaR1c4TDZ1VXNsQTZxWFFFVTFTSE40UE00eUpNNjNTNVJELXV1bHRjRW81Sk9JYjFFLXgwYjJEd0N4QUxvUjJVWjFUeGpJY1R2RXVncS1PUjVtMEZNcl9rUkxzZTFvbjJrSHNGY2FPUVlvSQ?oc=5"
    },
    {
      "title": "Week in Review: Ghosts and Guns",
      "source": "Balkan Insight",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Balkan Insight.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMie0FVX3lxTE5vQXZTRlVIc1lSZ2c5d3lkNUZjeUc4d2hPX2tnTmJSZkRqOHZxdFFuZVNEQXIyRnpMa1VuSmNYOUFEUmc4c2F4T3NWZXN2bXpYdHlhYU1fQjFKWXM2Z1ZVaDJrYjg0LTViWU93MERxWWpOd0tWcV90bG9vUQ?oc=5"
    },
    {
      "title": "COMMENTARY: Weekend Reads: Ghost data centers, critical-minerals backlash, Treasury's debt boom",
      "source": "Reuters",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Reuters.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi4gFBVV95cUxNcVVjMWRaVEtKRm1JMFMwZi1xeVhBaDQyOEd3Y3RSM05tZWNWUHllelZvNXJxNi0xckY5QWRncmF3RmJXR1NjVVpJOGh0anhCMUZrMXFhMTFaN1p0bnplclRfZG5PNTdlczhaeDNKV1Zaa1hiTE93cVcwZ2dYVnktOTI5dnJ5VXdEQ3lJVnNEd3hibVd2RnA4SU1IM1A2OGNJc1RJeTdMOTNJUzdqRWZOVEtqS3RBNml3T0FUby1BVDZMcTV4TWVZQnNyRXpsZ28ycGVZd3Jxdl9zVEN1Y2w3Znln?oc=5"
    }
  ],
  "us": [
    {
      "title": "Waiver Wire Week 24: Gasper the Friendly Ghost",
      "source": "Razzball",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Razzball.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTFBVVHBZQlFxbmllVU0wNGRhMGdxa25HMnVtMkU5bVRVaDdZRWdiV2pjZ1V1WWFxWFVNU1RscEkzai1UVUdMeWt5Qi1TcTBFWjE4YWxzdHpHQ3NHeVZkbTBFWExxeDBfYmNvaWc2NnBjMlh5U0x0T1E?oc=5"
    },
    {
      "title": "Ancient Mysteries and UFO Disclosure Take Center Stage at New Immersive Event",
      "source": "suindependent.com",
      "date": "2026-09-05",
      "excerpt": "Read the full story from suindependent.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxOb29kbHgyMUZ3MDJNeXZiajJSQXNwUkh1WDFXNDlGVVBrdlEwMUNNTDBhYk5jX19Za1RicWN2NEgwa3dKTGxBMlA1MFRJV1dWN2EyTHVhM3VPRkdsbVdUQm1PS0xoSkdDY3RzTTFjV1JPSEYwQktZektyclVlaFRHTUFnWFJZUTZBTjZjWWNTSGRGeXBuU0Q1VHFENDRldkRMZ3o2bi1zOA?oc=5"
    },
    {
      "title": "Michigan Haunted Trail Brings Cryptids and Creatures Into the Woods",
      "source": "Cars 108",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Cars 108.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE1WTldxWnpNbTNPT1dYNDBhM2lyRl95aXNXa0RWVVdmWGNpdzlxVWdOX2pCMDQxaFNhcGh2aHlBRHcyQWR6OVpLS2I0MU9jTVRPNTJ5YlZteVhTN1d2MkE?oc=5"
    },
    {
      "title": "Concept Artist Sam Rowan shares Grey Alien designs from Disclosure Day!",
      "source": "Scified",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Scified.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxPSVI1UzdtTEFoUHA0NVZlVlAtRzhCX3ZERjFqcm1aN0g0bTdKbXZtMkl6SVh1OEo3RDFFakZmZF83Y3ZlUi1xN0FIbHcxYUdCTFZVLVI1RGI0TlhJZnJRVzdTczA2Vm5mZGtLUDhWRmNpdENyU2pWZ1dSUHJKaEc0aVBNWE5ZS1d6eW51Y0dlcGFsQl9w?oc=5"
    },
    {
      "title": "Star of TV’s Ghost Hunters appears in Glasgow, Kentucky",
      "source": "issuewire.com",
      "date": "2026-09-05",
      "excerpt": "Read the full story from issuewire.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxQQzdsaTFsQzRKZzVPY2lfRE1GWk93elpGUVNqNF9HcUdkdjFlckN0cUFaRW4wRF9ZZlJjX21Ib2lyR3l2bktnTUdZdExqazhqVXM5SjJHX2I2ZkRBYjczb0l3V1hNQ0liQXY1MktHMDRKUXNzazlabTIzRkZ5SGRFSmdvZzVCbEVHMVlwRFZhUWVyWXNfcWVGR0NtNFY?oc=5"
    },
    {
      "title": "“Probably Includes a Couple of Ghosts,” “This Is Creepy”: Fans React to Historic Detail in Taylor Swift and Travis Kelce’s $5.35M Mansion",
      "source": "Yahoo",
      "date": "2026-09-05",
      "excerpt": "Read the full story from Yahoo.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxPQ1ZtNGp2amNEQUpqOGFYMkg5NFQ1eVA3S0tYcFpXUDhoTWZvc3ZIMzhfWnF2RE91ZVJFeUxmSmpCYXlaMy1kUE5zN1ZnQnY3dTMyWGJ1WFJfMmdEQm1GYkFwU1hJUlFtbWxaNEZtaGxTWjg3WGtwRlQ0QnJnc016TkMzYjRxaklJMXVNbEZxOHJ2SGZSVUd3OTFDYTNLUWt4a0RBclNBR05OUE4x?oc=5"
    },
    {
      "title": "‘Ghost stops’: Phoenix PD insiders say unreported stops happened in South Phoenix",
      "source": "ABC15 Arizona",
      "date": "2026-09-04",
      "excerpt": "Read the full story from ABC15 Arizona.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxQTTNGZFhQSHdLTUFVYnByOC05Y1RXcXdPcHpYYWRjU1RQTk1MdVR3X2c4VHJTQklsMjVudU9ENy1kbjN3OEozVk1vNlNaRUZtS0FXaDFuOG9fQ1FDd1NuZXMtQkFCT0lXc1FxTVZjbVNJQ2g3cEtMZFhVa3RrZDlZdUxQenZCazVXeGdLOHRlSjJVdXdvcU52cTVHb2o1d3BPZHlualRBNXVUZmZQa2ZaUmVSVjJieUxtdEdYRjNZeGxGczRmVTloOEI3VQ?oc=5"
    },
    {
      "title": "Aldi’s Viral Fabric Ghosts Are Back—and They Come With New Adorable Accessories",
      "source": "Dengarden",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Dengarden.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiigFBVV95cUxPMlppd2tjVjl2VF82RTE0TU4wVGxTRDBzRUVRVS1UQTBIZXdKSVE2WE9Ld2hjSzhHNnlJNElCckVTSXBGQl8yV1NSazB5QnFhZmpzVmZGVWh2Z25tQkZCcTBTajVzamlwVUdjN0tXVlNuQ2tBWGIwamp6VFo1U0RWUUloZVBDaWhVNEE?oc=5"
    },
    {
      "title": "Savannah homeowner seeks to preserve ‘ghost sign’ in Historic District",
      "source": "wjcl.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from wjcl.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxPQ1FYYWFtRXRQN0F0bG9YcklpSzl2ekpqcERqX2dRNURDYU43RjZYSUc1NVVzMXVoanBQNFZkVGNSXzJsaGdLVFNZS0V0YWZIb2FTV1Zmay1nMlRpc1I1SFh6cHgwRnVqSnhqTnh3SVRfbWNYLVlMS2ZyY0pfZXoxVEpUZlBhSWhHNzd2X0hsYkZmTVVQd3U4MThrWThOdkpfTDFaZk1Jb0pHQQ?oc=5"
    },
    {
      "title": "Paranormal Cirque brings horror-themed circus to Spokane Valley this Labor Day weekend",
      "source": "kxly.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from kxly.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi-wFBVV95cUxOVmwtT1RqeDUxZnhhQVVWSkloS3hnYUFXRkpoeHRRMnpQVFRPTGZIbWFhdnFvczhMVTlFc1BZUXdWTjY4V2p3TndIbWFjYS13YXRsT05oUFdJRkEySko2RUVjQVdmMHV6RTBrbEJQRUkwanFKb1JiQUZ4Y1RCano0R0psWnA5R1I1bHJRdnNZSTMyZXNvbDNYejVkTFNvWFJzcmpTZlFmZjVUMGVfdXpYNld2c2I1dVMtYmluMlB0MVhSdGhYVWc5dlJ3RzFKaW43LVktQjB1VGt2MDFEUE10MnpMZGlORVNiX0VpbDZ0UEZKTUh2ZVRqTEhaaw?oc=5"
    },
    {
      "title": "Coastal Ghost Scout Day: Data Dive Position Players",
      "source": "Prep Baseball",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Prep Baseball.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimgFBVV95cUxQaXFXSU4xdnNZWlBhaTdvSU1CWlRaanh4ek5zcWVLdFpXbG50TFFxX1V6bUdWZ2pmWnY3S3BET04zc1ljMTdNRnF1TUpnUWJOX1FPZENqdjk2eDVzRUpBY0JKcmRoQmwwZ2JDRWc1Zi1zYmNxRmcyaUhGN3VWdTY3U2hLb2dQRDlHRWpHaDR0RUhnaWF0NmlQOWVn?oc=5"
    },
    {
      "title": "Decades later, Richard Senate still has passion for the paranormal",
      "source": "Moorpark Acorn",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Moorpark Acorn.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxNV0FkR0FnbE5sQllOc3AyRkYxazBpTFVRQjBVOUFlTzdoaWFQWGpaV0hwVi0tLXI0R2VicUVqLUNDbko2bjk2eU43UE80Vzk2a3FNYkJ1eGZLWUN6aGhWX3VmcEZVMUJnR0dMek5CNy0zVVR6Si1vRVhJWV9paUpxRHl2c1lxQzFwclYtRFFCbnFGVEFEZHcyUlZOZHJzTWFs?oc=5"
    },
    {
      "title": "New Orleans’ Ghost Manor will return for Halloween in 2026 after being closed in 2025",
      "source": "wgno.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from wgno.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxQZGl0NkFvYzhmaUlid2UtOXY2NWktd2N2ZjROTmpjc0FMbXY4TUxoTUZCdnBHN3BmUDhiZWo1VFJUTVhzMnd4R3VsNUE3QjlSbEJtNUs2N0ZZVlJpdVRkZ2lYQTg3aFpZdWZ3MVpqXzRlczJxSjZ2SjBLdnpnV2ktMEdDbHo2WjhXdkwyYnlMdkRQQXliNVZScEhVTUhDc3pHNWNLN2l4ZFY0RnhLdXVqd1BlZ2xIamExZUhMWDFnQlZ0d2ZGVHRYX3dGXzLSAdIBQVVfeXFMTmc4aWprMUR4Zmp4ZjFKNWJtSV81ZHVHLWRROWdEYUt2cXRkUXFQc1ZOblA1LUxqaE5xRTZQWk5fSTdUY3Fjcld4Z3BxZFg4dTlBMU9SQ2xFcDZJYzN4Qzk0M1ZfdDZrVFB4TmRCU3EzMDZkNHc5Z0lrdVdRZHd4TVE1ZFktS3dta1k5X3c3Mldrc1dqQ2x2NklhaC11aGVsaUJXRGczSmNUOExZdThtb0duVlJ1UlRwZi1SQnBaYjBIZG5RXzBndzc5VDNjbVItMUVR?oc=5"
    },
    {
      "title": "A Mysterious Deep-Sea ‘Ghost Shark’ Is New to Science, Researchers Say",
      "source": "People.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from People.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxNaXBkdzA5X0xTU0h6RU1OWDNRbGpHRmxYalYwWnIyWG1FV0VtMkgxVncwUXY3OHg0S3k1VXYzcmNhTGhsbEVVNGFuQUNLNjA3Y3RfdnZyaGpVeFp4WGRVUlZBMFk1NE90TzNOM1ZQNnN6d2ZMcDk3Z3ZRSm11UHBKQzNOdFVDTWlGYnpURVg5WUl2dmVfR0V1Ng?oc=5"
    },
    {
      "title": "Paranormal Cirque comes to Spokane this Friday through Monday",
      "source": "kxly.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from kxly.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxObEpwUllKUnlCbkNEUzBYT3dRUHhEMzNFcHFwQlVONm9rS0h0M3Z3SVpKYWpXRUNHRV9lakNoSWx2YnVSbV96NXkwLTV0UEYwcFIzZ3B1ZGpvclZ0aGhPR052ZUFaQVZISFZQYUs5UjJvcHdjWk1mSXZSSDB1Zm9ndVJza2otSGJyajlRcnI0MlE4cWZtSkdwTjJSZ25hZlhjWTFvTTdXUmJtYUVHd09NNnlpOTNsMG1aT3dtT2FiN2g0a3ZkbXF4dDdfOVdOTEVVc2c?oc=5"
    },
    {
      "title": "The living care for ancestors and wandering spirits at Malaysia’s Hungry Ghost Festival",
      "source": "Front - The Journal",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Front - The Journal.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxNclFFN0VNRmtmdXdMN3E0dVoxWUVSYXNnSVJvcXgxZkxuTDBKMjY0WXlESzM2dkVkdDducEZ4SXBEbjhVM1UxN01mMVE2cmtqSEJyWFJxYWQ1dHYtcDlPRXJRYUdpWWhIQjVicDJHZHp0MTJucVhkQkJycUVFYVFJZVNTTUR1eXY2VVNFYWtGbWQxYk90N3hnZ0xmYXFKMU1lSkx4LTV5RmxsM3lrTWNSVVZPVDVrTWI3Zi1tTU5XeHIxdw?oc=5"
    },
    {
      "title": "Hope Director Na Hong-jin on What Aliens Reveal About Humanity and Capturing a Classic Sense of Action",
      "source": "The Film Stage",
      "date": "2026-09-04",
      "excerpt": "Read the full story from The Film Stage.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxObTBZN0dNSTEtVl8tcExxWGw0ZlBnOTFpWEtpUDBtSHF2ZThfWW9lWDhBSTFVRmZLS1p0SGdpYWRBLUtWcjRhQmlOWnBDVHdRakdJZW9fSURJS1ZpbmlzR2RXV2lGZ3dkelRWTXlSU0cwWEladS1SeHFvX1g1Ym9BalQ2UFNsTS1teUk2QXA0MkZ2bGtpclJwQTBDeHRETWtTdy1KUlB5Q3Aza0E1andQNXlEeVZHTUtubVJUMzBycGY0c0RWalBJ?oc=5"
    },
    {
      "title": "Ghosts & Goblins run returns this fall to support Carmel Clay Schools",
      "source": "The Hamilton County Reporter",
      "date": "2026-09-04",
      "excerpt": "Read the full story from The Hamilton County Reporter.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxOTzlZaEZiODN2Nno1b1RHYWdDcU5Ebm1Ba19UdlhSQVg4WnZ5R3JjVG1wMFQ5T2F6YVNBaTF5X0F3WUgxUVQyaFYyZFBFODRPMDJSLXRRUnpPRE9keGtBVlZ3WWdsWS1OOGpHazRsZUhRVmxrZjYxcnBHbEZtc1JHX2lLZ2FzVmdJOTJydnNsWGQtWWpNSE5RaUFfYlY?oc=5"
    },
    {
      "title": "Dr. Phil accuses US government of lying ‘straight to our face’ for ignoring legitimate UFO reports",
      "source": "New York Post",
      "date": "2026-09-04",
      "excerpt": "Read the full story from New York Post.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxOX0tEbVR3c19yRF93LWdvdHY0dTR4Tm9WaEtjdklkT0lUVTNyLW5EM29USkJUc1d0dEE1dnhJTEYyc1NiTDJLS25HVFFUcVR3MFY0QnlSYUxEbHVreG1JQVk5a1hfNVVNZVJlYm5PZlRZX0l4d3ppOXZUaHZiMEU4NHg2QkhHUGlRZ3djZ2s0NlpTMmRpTTBWbUc2aDZVU19IcWk1TlhWckVrSzFWOTdaQ3lvNTg?oc=5"
    },
    {
      "title": "The gospel in the context of Taiwan's ghost month",
      "source": "www.christiandaily.com",
      "date": "2026-09-04",
      "excerpt": "Read the full story from www.christiandaily.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxNWHhyTDJURHR6cjZ0aURhVUkxSWFpWWNKNWNMZng5cVg0TktJalRndUgxbHpsa0V2bDdxQ0lZdV9aNDJtVnFiaExGamZYa1NQSXdvcFNKSDJRLXN1RmpGN3d0WkpudWs5NmE0N0pZWUdxVTlTQktFQUhyTk9ycmdIM3NjeS1DRDJ2bzVJNFpR?oc=5"
    },
    {
      "title": "Exclusive / YouTube cracks down on ‘ghost creators’",
      "source": "Semafor",
      "date": "2026-09-04",
      "excerpt": "Read the full story from Semafor.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxQdmpCc09ZMndQUTI2d0VJYnhoWlV3OGh5dkpmTUZnMnByMG9vOHh1V21OTGt0SHFLemxVVXhCaDZfRUdJWUFoOXRVX1dLOG5ERmtkUE9zTFlwQVgxbUJEazVqSnFWeXZFems1ZWlOT1YzRmFYU0xSWUY5OVotZ1h6M0hGMV9VUGc?oc=5"
    },
    {
      "title": "Former Pentagon UAP Task Force leader Jay Stratton releasing book in October",
      "source": "KLAS 8 News Now",
      "date": "2026-09-03",
      "excerpt": "Read the full story from KLAS 8 News Now.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMid0FVX3lxTE9RY25jd1BJenJFay1kQ2RzRjFVNUdYdF95ZFZmZmlSclJtTkVDOHdXY1Y2RlZKVUU0ZjM3M1Z1M3lCV2lTSjV6NzkxZGNUaGk5SkYzM0M3S3p0WldkM1ZYdHRFVXA3U2FVOEwtNlJNLWt0Mnl6TzRv0gF8QVVfeXFMTVptVEhHaVAzRm9YdFRUbVhWQmVUdzdkUTcwUFpvN3psY0tvRWY1eDNLZnZQMEJCVWFncktVM1ZQeHdCMmhBdTl1ZndmRWFvSVg3RkY2YmZFbGdnMHNGTWNnYWtjOE4wVlU0YkppY2dmRW41M2J0cTdKVVVuQg?oc=5"
    },
    {
      "title": "It’s ‘John Wick’ Meets Bigfoot as Genre Banner Badlands Picks up Horror Script ‘Wildman’ (Exclusive)",
      "source": "The Hollywood Reporter",
      "date": "2026-09-03",
      "excerpt": "Read the full story from The Hollywood Reporter.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQWUk1LTcyNkFVbnk4NmNMR3A0Znd6NGhXN0FndHpQZllXODdaYnp0UjlSQmJpeFFwRlNtazRCZElSZnlETjlZUjZjQnV4UGI5ZEhCTGFsNVB1WTgtc0pzTFllZHBqRFQyV3NKVGhzUmNXS2hyTDIxbWM1NDdJU3IwV2NScEc1TjVfQUJWc0FpQXMyb2hxLTNmOC1Raw?oc=5"
    },
    {
      "title": "'Alien: Isolation 2': Facing a ruthless and evolved Xenomorph in our Gamescom hands-on preview",
      "source": "Space",
      "date": "2026-09-03",
      "excerpt": "Read the full story from Space.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxOQWt3bXNJYzFhc2E2LW9xb2VYZHdYdFh6eEhURExNR21VdnpMNlBEenlqdVFETG1vd1ZMaEYwOWh6WFZiWXplZjF5alppRVE5UGJMcDVkR3gybGktODk5UFpmOWNhSVU4bTkzWkhEX2ZWdGdMUGw1SENEbGwxSjk5bjByMVptRkYwVXhqbWprNXdsVkNJNEJKWmdIZ1RZXzdMdnJoOU9mc19LZXBSU3p0bWwzY0NCWlExMm9uQmxpRFZLd0hfR1huYVl3b2VmVzVDX2duZA?oc=5"
    }
  ]
};
