// AUTO-GENERATED by scripts/update-news.mjs via .github/workflows/update-news.yml
// Do not edit by hand — changes will be overwritten on the next scheduled run.
const newsData = {
  "updatedAt": "2026-08-21T01:26:20.747Z",
  "uk": [
    {
      "title": "Who's More Human Than a Child? Noah Hawley on Wendy, Humanity, and the Expanding World of “Alien: Earth”",
      "source": "Motion Picture Association",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Motion Picture Association.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxPd255SDJNejNqSXllRVFhODVaYmtucUZvX0U2Q0xfazRqM0FiaWVKUVdBaHdQUm9uR2NuOVAtV1laaWdZRWRYU01ZQWdQaGFSSDdGZUFGemVrWk5pUEZxN3NRMVFKSnJuUE5PZXk3Wng1Zm84OEQ2aHV4ZlQxamhPRTFvbEZtNU1PUGY0a2xxQnVNT3JSZWQ4ZjFjeVBSZHhGakdNZF8yZmxfeU0wMVllSFYtemQwSzdjWXI4MGYtaGphUkk5cDhtRzlFeVNRc0VCQ29j?oc=5"
    },
    {
      "title": "THE GHOST IN THE SHELL Anime Shares Special Video Featuring Mirai Moriyama Image Song",
      "source": "Crunchyroll",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Crunchyroll.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxPc1Nqc2dvMEVqNmF4bjBpcUllR2FfV1JoN0dlUThiaWw1eEUtcFpDbzUxMVFyV2Mxdm51b0JfckFORkNBTndaNlppRkZSTlhlNWk1TDgxdTduTVVaeFBGc1JRX2wtNS1SUGZUQzBPTUtvRDJiaWxJRG0yMUhycHEwM3hRWDhNZEdjRVVtbFJEZS0xckl1TXJXYkx1V1pGWnhFQlBDREhKYnhVUTJ5NWlV?oc=5"
    },
    {
      "title": "ICE Boston arrests previously removed criminal alien arraigned for vehicular homicide",
      "source": "ICE | U.S. Immigration and Customs Enforcement (.gov)",
      "date": "2026-08-19",
      "excerpt": "Read the full story from ICE | U.S. Immigration and Customs Enforcement (.gov).",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxOLUtjMUgwNE1iZEd1aHljYlZRNk9kMEd4X29NQ0lCQXctc3VTbkVUVTBQd21nZ3Q4QnVOV3Q3VUZ3aHFjNjVtOHZvd2dkN3BTU3Y1ZlRwd01IV2JRWHBLMDZxNnFzbTQ3RUlCanVlVm5lNW9UaDBOZTdYYUx1VzNFT2FhU0tGRFJCSGpBcWFlbEtVNlNEamFFU3RkNHVMemtITnFtQm9GN2phSFZtUFYzTWotakVuZw?oc=5"
    },
    {
      "title": "Ghosts of Amrum",
      "source": "The New York Review of Books",
      "date": "2026-08-19",
      "excerpt": "Read the full story from The New York Review of Books.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiakFVX3lxTFBiZnVTMl93VXNiVUhvZ3BoejhfQUplUlZpWjV4MWF4OTUwdTloY19mUDdXYkRjRWM0MlZVWWxsMmRiMUFsd0F6NkpYdGxldXVrQlR6SGl5QUNXZ3RReDhnRXZ3Ty1EVE1rMlE?oc=5"
    },
    {
      "title": "Firefly Aerospace Onboards Zeno Power on Blue Ghost Mission to Demonstrate Radioisotope Technologies to Survive the Lunar Night",
      "source": "Firefly Aerospace",
      "date": "2026-08-19",
      "excerpt": "Onboards Zeno Power on Blue Ghost Mission to Demonstrate Radioisotope Technologies to Survive the Lunar Night",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi7wFBVV95cUxPbi1KR1U0dDFXNHZHcUFtUUp4RjVybHVubkl3VTF6VEpLY1d0YjNNNjV6cUx6VzdlZmtxbS1yUmYxVkxlbDhERktIS2hMVWpZMDJnNkw0NVZJTWQ5UnZ0SGJlZTFtLUdJTngydjhzTXc3ZDVmM1ctMUdPZkdSODNOSng1MkRWMzJqTTBsbll6a25vbEgtUVdvZ01YS1BtbFJuZnJEb3lDMjk5bVFtLWR6MjRCZENPMGdBN0Y4bU5mSW1nZ3luSnUwTGdOMUl2WHItN25DWERCR0RYaTBfNklKOUFOWWFwcThJb243cXNHdw?oc=5"
    },
    {
      "title": "Voyage of the Rock Aliens & VHS Swap Meet",
      "source": "WAMC",
      "date": "2026-08-19",
      "excerpt": "Read the full story from WAMC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxQRjRESm9laHF3N3BsUGlFTlJhRnNKc1ZEQzB2VWxlSGttYjFEYWdvZlpGa0V1M21QT2hjZVZQd2JDb2s4WFFGcEcwNW41UjRxd3dzODJ3WEFKSHdCelFLVFhJWUFxTU5XWksxenNkaVVSTFUzQmJqb1VZYndxQlI3eVRSOHM5Z25wZ1R0eDRSRF91eVBKRmx1aWExUjljMUxTaDRmdTNRelhpZUVTcXc?oc=5"
    },
    {
      "title": "Mussolini’s Ghost — the strange, lasting legacy of Il Duce",
      "source": "Financial Times",
      "date": "2026-08-19",
      "excerpt": "Read the full story from Financial Times.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE00QzhWM0Q1ZWFDZ0c3Z05KX2FPX21SSGhDdjFIemxHbEZnTHRrSUFBN3JBa0ZlUDZUY1A2TUYyQ2V4R3F6S0pUUmhSOVZCbG43cXM3cnI4djQyVk0wbTZIUk5zRDhsS0FxYkNXcFlta2c?oc=5"
    },
    {
      "title": "Vans, ghosts, sofas and a kiss from Katy Perry: artist France-Lise McGurn and her paint-everything ethos",
      "source": "The Guardian",
      "date": "2026-08-18",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOZFpLQVVIYlgwdFlqMHNtR3o0WGMyazRsVmJIeUdUT2hLU3VobVVFZXJ5VnJwTXllTVZySDVWeEs2WWtWcUNvV2NKbDFsQ1JYblI4UGVIYUJNZDVBTy1mQ2xOZXBDZ3JfY3Q4VHlBMDc5NEQ0Um5JaC1DUm5jSVVobGVsNGYzeDRaMmctQW5kQlJsYU5fVDdhOGxBTGdPUURURGc3QXYtVHVBSmZkNlQ3c2JkQ3h4Z1FE?oc=5"
    },
    {
      "title": "Iraq’s ghost villages: Islamic State drove people away – now a new enemy is preventing their return",
      "source": "The Guardian",
      "date": "2026-08-18",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxQN3ZYN2VJS2JPM2tTbjV6Q1NNbWFOZmN6bm9mczNoLWt6WEJoc3gxb3J0N3FoX29wRjZIZnVJWGFiRlY0RmQ3NWpxb2lMdUMxUTRlc1ViemRJak1Ha1hzS2FQLUhWSEc5NE1LRWN0cEd1UUYxZVlwQ0J6YlZpdVZaenF2ZTFrclE2cG1CeHhvVGJyUGkwN2ZmZlJyX0Z1eHpYWHR1RTVuRFJDa1oxbXk0?oc=5"
    },
    {
      "title": "Lanterns review – Kyle Chandler and Aaron Pierre’s alien-hunting superhero caper is a bust",
      "source": "The Guardian",
      "date": "2026-08-17",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxPS19HY0JtSEt4VUFGcU4wVXM5SHFsbjFqN3VEZzBnRjJPSmhVR0I1VDI2RkJhcG0xQnJiNC1Nd1pVZ1pjRVFMdTFiWnpxYzlKeXNVOHRvMmpEYUVOcHNUZHF1WmtKd1g1cDFlTV9TSF84SVpHZ2Ffb3RIZ1BOMjNUWnBkdVVRbkRrZTlmaHpnWnF5NVNqWC0tMjRtWXZEaXpVQjN4VF9SQ2hHdkhtNkZQVHBLR291UnF4NFluYm40TkdUdXR2TmVBY09wb2s1cnNjeTkxNw?oc=5"
    },
    {
      "title": "'Alien Vs. X-Men' Pits Mutantkind Against the Deadliest Species in the Galaxy",
      "source": "Marvel.com",
      "date": "2026-08-13",
      "excerpt": "Read the full story from Marvel.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNdlRNcDRsajB1YnpGaGFmU1luOHZ3X0h6eXdpZi1TUGd1Q0VhX1ZjdDZSaDlOMXc1bXJkNHllOEMxcGdJeGRLeDlaN3g2bXFwSWpSclBTV0ZXZUhHZXAyY3VocHBuUVZlZ1A2YmxFT0F5VFI3c01ubGtkUjdiV1Q5MGFFcmYxcVhJQWxueWFLOEtiaDRHeEZDRkJEdG5KZHJLNXlpRW1nckF6SXM?oc=5"
    },
    {
      "title": "The Freaky, Tentacled ‘Alien’ Bait Turning American Fishing Upside Down",
      "source": "WSJ",
      "date": "2026-08-12",
      "excerpt": "Read the full story from WSJ.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxONEgyZjJZcFF2c3dJOTBFRC1Ub05XUUhwT0k1SEpub3h4X0NiZEllbzI4UFEzaS0yblVBZ3RnRUFHcklGeTdqdDJEcmNmcXpHbWh1eVptVkJJSkR2ellHaWxZbmVUczg0QjhoaS1iSVRvZTFNeHJsZURnOEI5TFFWaFBkVDEyOVMzeDNzTmZPZXh0N01ydHNvUlZaWWc1NkxUZzJValhKOA?oc=5"
    },
    {
      "title": "The great silence: why haven’t we found any aliens yet?",
      "source": "The Guardian",
      "date": "2026-08-11",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxQN01nZWZBRE1NOEdrMGRkUDh3UkxQN0hDQmZkVnV6ODhsNFdVbGs5NHd5VjNIYndCWFUtUXlvaEJ3MF80SVhORi04dUlyUWp4bkJXbTVjWVlhN0s4VDNqX294NEF5OEF4QTE1Sm9XSEEyXzhpaXREUFR5SUd4bE8wbWw3RUR3MWdNejc0UFEyM0xlTFI3ZGpGMjg3Sm9sdw?oc=5"
    },
    {
      "title": "Pentagon releases fresh batch of UFO files",
      "source": "BBC",
      "date": "2026-08-07",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTFBGNjdZaXNSbFNGN1dHdk1tQkx0aXo5V0VEczJYSWxvT0ZQY2ZsRGdHZFU3dDhvekpnV1pPNlVIZWlWQ0RfVHN4aUh3a3V1SlEybFE0bHI1SXpJUQ?oc=5"
    },
    {
      "title": "Department of War Publishes Fifth Release of Unidentified Anomalous Phenomena Files on WAR.GOV/UFO",
      "source": "U.S. Department of War (.gov)",
      "date": "2026-08-07",
      "excerpt": "Read the full story from U.S. Department of War (.gov).",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxNaHJtX1ZyZFY5aXFyd29oeDBjY2xxbTVuaW4xeDU3cjZ3Ml9rY1c1cE5zQXJ2RFE0YTR6NjZRRHo1SmhCUHpFSUsxVG9zRlJzNUZpZGpFd0lMOExjUjJWN0E5OTYwa09XbVpaRHMyZXNLaWpad3VpMndsc2taVjdvTzVaX21kcG1ENHJvcnlJQXNmdXZWMTBmQkkxYk4tU2VpcWVuTDZ6eUFEOWdOUEU1N2kxRE90NEF0VlFCOHc0UkJoTTdfQ1JNbDNVUTUyemlvcHd4MA?oc=5"
    },
    {
      "title": "Watch: Pentagon releases fresh UFO videos in new document dump",
      "source": "BBC",
      "date": "2026-08-07",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiV0FVX3lxTFBYREVGSVMweGZIQTM1YXpYQ0ZjNkkwTjloMVB4M0NkN092d28yQnBCdHR2MlpfMVExZm5EYnd6cGxpWktjM28ySXRudnFjTTlhUjlnY2dOWQ?oc=5"
    },
    {
      "title": "Traces of Two Extinct 'Ghost' Ancestors Were Found Hiding in Modern Human DNA, Hinting at Our Extremely Complex Family Tree",
      "source": "Smithsonian Magazine",
      "date": "2026-08-07",
      "excerpt": "Read the full story from Smithsonian Magazine.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMigwJBVV95cUxPdDBJWUtfWk5ZcXFxZ0Y5SGNwRFowSkJtZUxPeGE5SG93UkhFLWFIRGxWb3FzNnhrQTBXdG92QWJ3Y3pIaUZGS3JTZkhKaU9vVlFzZGVvTm95LWhXNWExcnFSWEl4Z3NwM3VfNHltaVNlZXdSRW5ua0hsZlhldjhiSWVlMVlubkhKejVfZFQ5YThRdU1DNk1adHpfSDZNeDBsbFM1UjlZd1lnc1BuSFA2eEs2OGRPV3lyblpnV01xRlRkSHdGOFFzUzhnZ3lpVXhSTmdCZmZySm45ZmE4WjJaUHNWaEpQUDNabjQxQklUSnBMS1ppcUh3cGstMF8xb29URVN3?oc=5"
    },
    {
      "title": "Latest Pentagon UFO files release includes video of mysterious ‘cold orbs’",
      "source": "Scientific American",
      "date": "2026-08-07",
      "excerpt": "Read the full story from Scientific American.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxOdzJvODkzOE91X0VOOHZzdC1zcWdYemNzQmotZzZiQjlQRnNTbWt5VFRWdFI3eVo1NWZrTVdPeHM2NEJaTW0yNG51akhmMlQyVEpZUWh2TFFzV1lJa05xTDAyNTEzWENmeHdJcjdNUU1EOTF5UWlZTTd2WjFmT0N1YURfYm1mZEsyVV9BOExVWFZyaVl3YWpraTJfNkJjaHRoc2VlMG9pbngyWDlmMFA0T2pXUHZiWE0?oc=5"
    },
    {
      "title": "Presidential Unsealing and Reporting System for UAP Encounters (PURSUE)",
      "source": "U.S. Department of War (.gov)",
      "date": "2026-08-04",
      "excerpt": "Read the full story from U.S. Department of War (.gov).",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE14VzNpMEZ3V21pVnY0aG9wWXl4Zk1jSmlzOVExVFlPcHRvb0NwWm9IZmJSTVZUS1NwdDBtaUxvdTRoMzJPT1JtaV9QZDUzOV8taEJnc0JKR0szSDA?oc=5"
    },
    {
      "title": "Ghosts: The Possession of Button House first-look image released",
      "source": "BBC",
      "date": "2026-07-30",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxQUjlkRXJwM1NRZVdncUdMMHNndzFnaUVGLXRXT3hfbzdyMFd6VEhCek9hcE5LU1hqV2pycndqbkp0aGVWMDdkZ09CMkp0UjROZUhzSUR6SUhiQTNJWFJic2VtZ3ZULWZKejVDdEkwM3RPWUlqVlBPUDE3djdVY0F3NS1sUHk3cHNWbTFDZjR3?oc=5"
    },
    {
      "title": "UFOs: What are they and what are the most famous sightings?",
      "source": "BBC",
      "date": "2026-07-22",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE93U1JQeHpqVVg4ZDFlQ2Y4MUlVdi1EaE9LT29ySXBNcm95d0lBUnhibW9oNzNLZEpBaVBMVFJRaXVNbGVsXzRueF9lcnVpSGFYME5NelI3b0ZLMEE?oc=5"
    },
    {
      "title": "Michael Sheen stars in comedy about UFOs after claiming he saw one over hometown",
      "source": "BBC",
      "date": "2026-07-15",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiXEFVX3lxTE1kOVhSZHFpMDhSVlk4UlBvYzNiUkV0Z1BUcEc3R2ppVnpHU1lZMEpLV0M0X2RHR2lNSHM5NWluclVRU2o5SmZjcmdfV2dOdzBVelExeFJ5eDFvSGhX?oc=5"
    },
    {
      "title": "Alien World Chemistry Found Inside Meteorite That Struck New Jersey home",
      "source": "SETI Institute",
      "date": "2026-07-15",
      "excerpt": "Read the full story from SETI Institute.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMie0FVX3lxTE5sa3BJTGhER1pjRUw4WHZ0WFpJQ2ZPQlpxLS1hbUtEOWlOVEl6RmRLSUVocVJjdEdYckU3VEcxcHdFc05PS0VQOVpRZjVxN3pJR1V0UGZ0UkpVSlc3MHVoNXMtSng1R2wyVExqWjlyZVN6Tmpka05CaExxOA?oc=5"
    },
    {
      "title": "Pentagon releases new UFO files",
      "source": "CNN",
      "date": "2026-07-11",
      "excerpt": "Read the full story from CNN.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxOV3VOM2hYdVhfT05lTEV5Yk9HVkY0SUhsSXFiRnFidEpSODdTdktHUXg3U3p3ekpybk9IN2MybS1NamM0YW5hZzhHRExfTEpaNjN6b2dXTHBRM0FrSDV1VGpOUDBBcjl0VzB0TTl6NXItWm10dnhCTE9BQUdCQmlPdDhUeVBiNUVsV09XU28wX1FzaG9MR2JKSmVvQ2x2c19jeDZtQ1FyMA?oc=5"
    }
  ],
  "europe": [
    {
      "title": "SCARPA unveils Alien Ultra, Alien Sky: Next generation of pinnacle trail-running shoes",
      "source": "Outdoor Sportswire",
      "date": "2026-08-21",
      "excerpt": "Read the full story from Outdoor Sportswire.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxOa2pKbDhDeE9BMkg5d0NHZmd5TU5sdl8xNkU2SGtjc3FZaUR2VFBkaldUTDF4LU4yRWNjS3EtVzRmMUNpbkRseXNXQl9vVDh0OVVMWTEwMjU2ZW1rV0J2Q1ZLTHptc1hudTdjdjNhREE0TF91QzB2cExsMWlCTi02ejViTjYtQ043TTFBTjlkbFdyVnllaWRxSGdNQVNUQVNaOU56ODZwMmk1UkxQNEdZYXBWX2hlTkViaDZB?oc=5"
    },
    {
      "title": "New Music Radar: Wack, Ghost Ochre and Paige England -",
      "source": "Happy Mag",
      "date": "2026-08-21",
      "excerpt": "Read the full story from Happy Mag.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMie0FVX3lxTE8wWlJBX2hEdWZpanpla0JnbHJYZmZZcEQwRUVBTFhCUHIzZGsxVVNJWjdGbE1oSlFQQXVQWVN3bW1KaGdIQVNlZVVNOU5lWWZHeEROR1FTWHZ0dXE5THQ5eFRjOTRJMzJkbU9OckRKX29OUlNpWUR3NHpWTQ?oc=5"
    },
    {
      "title": "BBC unveils first look at haunting new ghost story The Witch Farm - as Peter Kay's Car Share star joins cast",
      "source": "Radio Times",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Radio Times.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxQYy15ckNEMkE1WTdvSjZqQmdCY0RuMnNOeVVxV2tqbnJWdGJpcTR6aVRGN0E1c3k0elpxeXZJSVVrQ0RlMS1ZRTZXMGpaZmU2R0xqTnFpcE84WV81OVprUm96X1ZUMnRTUEQ1LTI2YTFzSHROMnZCcFpLNm1EWTNudXY3MUJfZEpVcWN4RWlsRmtYemVnazdPT1ViNjhhbU1LTVV4M2E5OVJDVGc?oc=5"
    },
    {
      "title": "Gaza and the ghosts of African internationalism",
      "source": "Mail & Guardian",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Mail & Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxQVnBSS1dyLVZGTGlfcmRBczRFMGItLVJDRENhemFCeVNFQ1VlbmhEd1haT0d1NEc4ZUIwM2JCZlZoNmhlck1pMW9TTkpSVzYyQUhOTXVGd182aVZoZ014M044WXZhTUhORGlMZEk3Unl1OTI1WFBtcjBsYzFqUjEtZ21SUDRWbnhkd3Vv?oc=5"
    },
    {
      "title": "THUNDERLIPS Are Taking ‘Mum, I’m Alien Pregnant’ on Tour",
      "source": "Rolling Stone Australia",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Rolling Stone Australia.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxOWVRJelFsTmpOR090aS12VEN4Y1dkWldvUFRBUTI2UHJNOHZBeE9PTUs5dGNiUGNxSkU3ckFmNGJpc19JTHVOMGYtZV9xVXVzWF9YN2l4LXZYTFUtbFRmRGkwYUpmYkRpbWtXNWJMZXBTWjhRLUtHeGFEWmttYTJVbEVnNUVKNjRlVkNjNnU2RWVaSkdBNlpMaUFsLWVlNkhROU9ZM01oRWZoU0FvaE8yVA?oc=5"
    },
    {
      "title": "Wolves in the Throne Room Share \"Ghosts Among The Obelisks\"",
      "source": "Ghettoblaster Magazine",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Ghettoblaster Magazine.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiowFBVV95cUxNOUplZzdZSlk0Wm82bUM0emdTZ0kyVlBZQjRUQ3NNVFltZzQ2QmVVZVF4Wm5JaFBKNW5zZU5vcHhYT09vODhHZ3N5R3FRM01TX3RIbzJQR1VaVUl3RnZhUWJhMWppRG1WMkM0Xy1ITnJEX0RfaGZSZ3ZyMmM0Rk1UcURjSFBhaUtBOGwwRGVtcnFQbWZCZXAxREJxLVFiX0JXd3dr?oc=5"
    },
    {
      "title": "Healthy Seas Is Working to Remove ‘Ghost Nets’ From the Ocean",
      "source": "The Inertia",
      "date": "2026-08-20",
      "excerpt": "Read the full story from The Inertia.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMie0FVX3lxTE5SYk9EVFUwYkxKU0VYS1Q3MTJNdnk1cXBIc1JEUWFKeEdMNzVVTGxBRWhlT2E0NHdQSVh2WHMtQV9INlBaQkJxRkdIclpZbUlqRGk5TDE5TGRvYVpRdS1KcGxuNGZDVGlVMUhXVUVGdEZ6VHN1a21pTzhZYw?oc=5"
    },
    {
      "title": "Jim Caviezel Goes Full Jason Statham in Action-Thriller Ghost Soldier",
      "source": "Polygon.com",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Polygon.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxNaGxjQmhRcjhzeFBFbDNKUkRISVJXMVNkVlp5U2NPNS1GRUtCMHpKTHlPblBYRGU5M3dRQ19Vb2NDOEFSVVo3VTE1NXJEekZ6Z0EtNS13d0RTMGZzWHgzZ0FuRElyTGNiOUF5RTItZlRMckZxRXpPR1ZnVE1Ud254ZFhST1E?oc=5"
    },
    {
      "title": "Ghosts Behind Glass: Encountering Extinction in Museums by Dolly Jørgensen",
      "source": "California Review of Books",
      "date": "2026-08-20",
      "excerpt": "Read the full story from California Review of Books.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxQaDAzSUpkbFBUdGh3SUdCMHhBSndNdVNDMjVPUXFySnN4VFR1UEtIZnJ6NjJMT091VXRJOGFvOFp0M21IRnM1Rlo0dWJmemlIZmZUMkl5ek9MWFdQS2dQNDI2c1pOamFYdjZWV3N0QzVTQ0JiRDFxQ2ZmZlhFLUZnMlYwNlByWER4UjR1R2hBWmhrMzVBWkZLRQ?oc=5"
    },
    {
      "title": "The Ghost of 1953 and the Unfinished Quest for Iranian Sovereignty",
      "source": "National Council of Resistance of Iran - NCRI",
      "date": "2026-08-20",
      "excerpt": "Read the full story from National Council of Resistance of Iran - NCRI.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxPNGFteV8tVk92b0tFZERLM2dQWFFibVhuOHptU1gwaFV0VDlPbTJOakIzak82akJ2azAzbm53VlB3TUd1WVlNb3ZVRGh4MjkxeVNxQlVPSzdEbElmcUh1OEZuRkkwby16cjBkN19hTnRIQV8yMjlIaEJaRmRKelRlYnY4TVpZVjZEbkhtT2pLLTIxU2VyWkI4Zng4clZ2bnVnd2EtUHFEblBzMEFDT3lTSWlaeUpSRFk?oc=5"
    },
    {
      "title": "Hollywood turns Americans into alien-believers?",
      "source": "The News International",
      "date": "2026-08-20",
      "excerpt": "Read the full story from The News International.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxNbTRpV0dhM0p5cjY5NmFUVWFXOWJjU2x6UU82ekN3cTZWZFVoU1M1b1A2Yk94dllGTG93Z19UNXJKanhHeENjMXFwSEZ1Q21qRmVwZ1VoUkhNczNXSmJXUDd2eDZvV3dDRHYtOHU3SS1PUWxwNG1nbml2eTVZTDlPV1FWelYtQjB3S0YxNmtEY2l4Z9IBjgFBVV95cUxPWjZNRUpOTEM1RDRSaUlPQlZ3aEFLeUxPbUlSd2ZmbGpOYW1NdEdWMUxkWEdWa3I2ek9YVFhpbjFFanVBYXQ0bGxfVHBoWE9IQzV1SGt4QTBRamNoQjhDSGthQm16N1pFYjNEYjB4aEpIdjMtMkxUeGR1anFWamxkd1Y2VHJSRkI1YzNsVlRB?oc=5"
    },
    {
      "title": "The Playbook: Why hiring managers are embracing ghost job postings",
      "source": "The Business Journals",
      "date": "2026-08-20",
      "excerpt": "Read the full story from The Business Journals.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxPajZJX1oxY1BLaVV4Mm90WG9kQ3VZQmVrVzM5RFdpWk5lM1hOVkhtYW12VkRIb24wTzNheW1IYWJ4OEdMZjRPWXV4Q2c4T2pRUGhvN0hBODNYVkFzU3hhT1g2ekY1YU1hZUxLS01jREIwMkdfY1ZqbjdtZTRRQzMzZlVWbFJmRWh0MUlQcWVLTWcyY1RpcFU4anh0N1JDMEdLYlVBMm5XOA?oc=5"
    },
    {
      "title": "Salt Hank’s, the Viral French Dip Shop, Is Now Owned by Ghost Kitchen Company Wonder",
      "source": "Eater New York",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Eater New York.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxNLXUtZjRTcW5OTlZJc0VfUWluVTl3ZEJHMTVKX3NaY2FZTEV1djhaSnNBNS1JYkhfR1lKYmV5WFVHa2ZGa3pQZFo0aHdRX1JUVG1MbS1lTnlFZFd3T2FsMmg0bzZqZEpBTHJMaDdMT2sxVmNWdzBHLVA1dk1UblRnSmFIS3poQ2hYRm5nZFZKNnNVVlBOaURJY2diSDJLNEsySTRINWNlUQ?oc=5"
    },
    {
      "title": "UFO news effect? More say they believe in aliens",
      "source": "Newsbug.info",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Newsbug.info.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi2gJBVV95cUxOeFNhcGxPYXpIYUdnRVBkMUZlQ2dGNjZwajBOdjQxYmVPeUhQMjdOXzhjYVRnTm9RNFJuWktfNjAta0l4RHQtX21IQUxKNFRWNllDUnVDd0VaalVrdTVNVk03cUVaeC04clhROUtZaktKRnRmdnJxd3hvQnpDRGl2b1JrQk9LLVZDUUZqOU1BaDV2eU1RWUxxMTZLOVBmclduTUlnLVhSODIzZTdFY0swVFl1eHFGUTV5SlhEcUd6RzgyQXFXX0NsaUh5ZEJPLW1YUnNhQThpTzRiekFjdEZuOFV3YW1wZUpfZTZzRE5zNGg3S3JIUVJ6LWpjVm9WNlFSRUhRUml6d1AxWXlueUw2N0lQMjR3dld4dTI4aE5tMHdPaHotUUxLd3BQVThCYVJrb0lCRFpsTU5xWEZXWm9UNURFampjdTN2N2htb3VPSjhJYnZycXRhTEFn?oc=5"
    },
    {
      "title": "Onlyplay launches Bigfoot Riches",
      "source": "Focus Gaming News",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Focus Gaming News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiYkFVX3lxTE1ZbDFEaEJLZHcwZnJ4S0RqbE9FODZPQnlTTGIxd3luTUFma2RDZ1JWek9rSGt5ZXp6dVpYVnBiQWF1LXc0YlRUZ3V2YXR3TDJnNm9NYkZOT2VGNHA2Z2RKQjJR?oc=5"
    },
    {
      "title": "'Ghost Soldier' star Jim Caviezel says audiences are hungry for heroes as he takes on intense new role",
      "source": "Fox News",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Fox News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxORzVnSG5zLU5fczJKU1lKRTdqMThaQktaeHg3RWRkRERpNENjc0FCS1NXbnVHN2hGbnpPeWI4N09ha25aOTk2UU9oczZXSXpQeHNSUVJYaHhDSkd3NWduQkVCUDNmX1BSSlYtbDRNTnlmSnBpTWs2X2J2TlMzVWxWS3RXZnVObUFPRFZ4M0prNXdiNWFkSG1VVWhvWk1OYmtRUFRySlFvVFNaODdwYUFmaVFUWXh5QmlHYjBvSGx30gHDAUFVX3lxTE5MRWNXeUozbXlCTzJSbzhxRnhzUnphdnRNSlhMMWdIbThhYWlHOEY0Vk8ydk5UN2RfRlY4dEYybzN0aHNBQ0RVTmFSMGMwNjFzcWd0WjVnY040UVYxN0ZfMkJHNjNYZjJXWjhPVW5pRHFpZHlrM1FtMkRIZ2VYZEE3bUItbnpwMlpwUm50SG5RbUR6VHdvX2tUR0EwWGkyZGJRbV8zVUZxVU1YZGt6T2ZWWXdMRUpUT1pGbjAtNU5PMy1Obw?oc=5"
    },
    {
      "title": "Smoky Eyes, Blurred Lines, & Ghost Lashes—These Are The Fall Makeup Trends Experts Are Coveting",
      "source": "Coveteur",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Coveteur.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiV0FVX3lxTE01WXRWakN0aV9YcnMxMlRBUFdkdWszM0Z6TU5ybXJlQ2l5MUFnMG9WajFCQWlVQUt4M1Y4VjVJdTlrMnFzckJnTGFzUHRadUlBdVRPckZOZw?oc=5"
    },
    {
      "title": "Harley-Davidson Ghost Drenched in Silver and Chrome Looks Almost See-Through",
      "source": "autoevolution",
      "date": "2026-08-20",
      "excerpt": "Read the full story from autoevolution.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxPQWV4aGcyc1BqYzJnc1BkcXhVeklTbHhyemNJNDBfMlNGQ0F6aDE4MlhzVXB2VEpXM3BGWUtnQU0wU0loTXhNQzhWaGpvUFdEOTZ6MVRFTHRoU0FDT3RvMU9mblEya0lNS0RKWVlqVFZoMktNVmRFT285bnJnTUlGVEdtdHVjU0RrVVNMOW9CZmF4WlBTTTZ1RE1uT2hJSWVtMlBIN2EzVUVsTk85SFNQQXJFNTkyTTc4ejBkQlhCaWo?oc=5"
    },
    {
      "title": "Scientists Just Analyzed More Than 100 UAP Videos Released by the Pentagon’s ‘PURSUE’ Program—This is What They Learned",
      "source": "The Debrief",
      "date": "2026-08-20",
      "excerpt": "Read the full story from The Debrief.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxQcW5fU3I5TVRSXzlnMGN2dG5vSUhtTkNYdWFQaW5SSG1PTDl2Y0hHWjlYSEdSTXBQMkM3UXlMSzJDdDQ1REg0V09adlFkaTE2akIzTENxOVlid0dmdEVGNDBLbi1FY1YzY2czRHg0TDltS0lkZTFkX0lMa05HZXRmZXFqV0ZZM2ZMa295UXVYSlQzSVVSOUxzbGlUU2cyQUx0Q3BHNHRNdmxmbGVvX19QNVFLUGVDajR2T2RsRVhMNFJ2YmtSdDVCeXhwclg0dmJ6RWwtLVVWcw?oc=5"
    },
    {
      "title": "Fatih Akin to open San Sebastián with Ghost Song",
      "source": "Cineuropa",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Cineuropa.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE1UMV80ZHhYMkltOHFpWm1PeUZfWmRxaUxCQnFyNl9HcjkweTdZWktzYW5mWFdrS09tSTg1QTJ2ekN4LTFfRUlKSnhJWDVqSF9CWVhDUA?oc=5"
    },
    {
      "title": "Talking Screens, August 21-27, 2026: Olivier Assayas’ Parisian Ghost Story | Orson Welles’ Greatest Trick | Music Box’s “Five By William Castle”",
      "source": "Newcity Film",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Newcity Film.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiggJBVV95cUxQMVVqUXhMX241Nkl6ei1BOG5KLUtBTnpNQmtQSWVya1hfMHB0ZUhyX2tfanY5QzExUXJrZ1NHbmhMTmVRVnBNTGlaQXhETW8xVzJmcEtqZUVUdXQ5cDd6RUppb0ZuWkFYOUhiZVNYOThrZW5lYm1maGtJMUxQY3BzaG5RMjBodlltWGNCNjE1Ukp5Z1d2TFhoMlRWZFM5OVZJOTVtb3VZOGdGQVB4SWl2bjZ2bEZuTWgzNTFhMkVTMV9vSDVtNFpwVmFQUFZfbHJtREJvbFNxOVcwOURCb251dWhnVTJMa2V2cHZGc1ZHeVhMYWlqVklPSk1pTEVVTFBUemc?oc=5"
    },
    {
      "title": "Before You Watch Insidious: Out of the Further, Here's a Refresher on the Most Menacing Ghosts of the Series",
      "source": "IGN",
      "date": "2026-08-20",
      "excerpt": "Read the full story from IGN.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxPVGFRa0JRbXJzYUJTZi1nN3ZaQmw4Y0hQYmNFREEzZWx3WkNCR1lVRThjRmd1QllQdEo5eDhRcXA5LTNVTjlnZ2pUeVJNZEI5WlpQMjZZeS1ubUViMXY4SnhYQzhqZm1feGtBRU9VZ3luM3h4RVRaSWZQVnNnZXBYMjJIeURQLVJ1djhiRzVmNTdMQQ?oc=5"
    },
    {
      "title": "A tech campus in Malaysia’s $100 billion ghost city got shut down. One crypto executive is on a mission to revive it.",
      "source": "Business Insider",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Business Insider.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxONjJSUERmMEdiZW9uOFExUVNxYnNHT19MX3loMEtCVVRuXzI3NzBaZmNXNzJtRlhFX1lWYjMySXYxM1hxNUFPcEtBeXZ4RlNsN1JPQUZwMHhOMnAxR1RlUzdoM2VlR2U5V1JoVDk0Y3pfOGdLRnhZSjRwd3NpeWZLNWRjYWtkZ3pjbWJ1NjZVOWxXVnhJYnVCZ3RrRXJ1NWNoY1E?oc=5"
    },
    {
      "title": "UFO news effect? More say they believe in aliens",
      "source": "Talker Research",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Talker Research.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxNd0lQT0JiTUtJR1ItRnFSMDFtSUxRbWRTM3RGRldoQm9KUGdJUjlFVmRaQ2gwUktLeEJ4VTNuMjczel9fNThBTHhoQUJkYnBXNFpHeU5Sdm5CWVBuYUtadmFwNTRIdWxxeHJJTEQyeU1ZT2wtVUtGNnp4NVgxNFJ5WQ?oc=5"
    }
  ],
  "us": [
    {
      "title": "UFO news effect? More say they believe in aliens",
      "source": "The Daily Gazette",
      "date": "2026-08-21",
      "excerpt": "Read the full story from The Daily Gazette.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxQTXdZRDh1MUFwQWZFZE1lWDYzMGphMUpQbElqVF95VlVFWktEQkl2VVhRTXZwZ3FSR0pCSXZTdEtndlBncEJIZURCTUREY0dMaUdFOFJ3bEZPWVpEcVNCUWdoYlM2bFNSTnpwN1c0SW9feVo0bksyRWMyZlZQT2NXNlNYQmdKempXXzBvMFZFLWlENlh1cmI5aEtWVy03YzZyMTNTX3FjZjE3Z2wxQmoyNVhlX0dBM3FtMHhGSUY1bDFPcFZBbUpiRG1iU3dsVDRiM2xWemV3bw?oc=5"
    },
    {
      "title": "Bigfoot body: discovery or elaborate hoax?",
      "source": "WOWK 13 News",
      "date": "2026-08-20",
      "excerpt": "Read the full story from WOWK 13 News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMikAFBVV95cUxOYzJkeUtvbVJGNmU5bFAzSEl4RnlKRUhjN0UwTElDak1PTXNpREJveEVZOVRoNzg5NDh5WFdkSi1teXZ4S3k5TVBDaXFiX1J5Z2E3ajFOVWhCRUYzS29SNW5fb0NZQ0QxVlZERGduckN1R3lwQV9MVkNUNHBId0dBMnd6Zm1hSUNFRUs2eXh2dmfSAZYBQVVfeXFMT0dwVWgwY0lkMUJCdkE2LWduQW5zMVE3Rmp2cGVOWHNDZXRzNjhBQzZoV1BaUUxsaTRpazU2RVVTWXNDWUZtcG5xWTRMX0FzMVpFQ0pXU0FqaEFFOS1PeHo5d2dmaU92UmxKTEJ2RnN3N1N2LW9PVUdtVHBWSkhYTEZ4RG5xMFRPV3ZhaTRhaDlFM0JNV2hn?oc=5"
    },
    {
      "title": "Ghost Face Takes Over Angry Orchard Cans For Halloween",
      "source": "Bleeding Cool News",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Bleeding Cool News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxPaGlYV2JFU1dYcUJsYlI1ak84bFRwSjZwdGFQVUxKbDBXXzdzVGVzejNzS2dMYUhoMUpNQi1tQ2hxN2ZxWHo1QUhsM0JNZ1ZESmp5TFhyNFNYMTdKQng1TTJwRVUza0ZHRjl1STlPdWxiQ2QzZEszRThvQ1c0LUhDWDk0VkY2cXY1LUpCS3k1d3lCdHltMGpJ?oc=5"
    },
    {
      "title": "Piano-Pop Trio Jukebox The Ghost Headlines LeFrak Center’s “Glide & Groove” Series",
      "source": "That Eric Alper",
      "date": "2026-08-20",
      "excerpt": "Read the full story from That Eric Alper.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxPRk55alhCeVZuTzJGZldxbW5CV0FReW8tMGZxdjdPWVF3bE80ai11YkF0enNkV2tSM0F5YkZ1T0MxR2Q4Y2JlQTVEajhzOVZJZGpmeFhyYjNtOEwwMkIwVUhrc1lPZ1lLZldVaEY5c1ZLQzd0UFhVZ3FsYm1MUFNTTGtFTWVOcUxSa3dvWmJwWTRaT0U5RFZCWVN3b2xQekFxd3paWHFYRDVQWWlPY1BaMEdUZEQwbVRKdWdF?oc=5"
    },
    {
      "title": "End of the Fair, Downtown Distilled, Paranormal Cirque, SeaFeast and more | Lifestyle Lookout",
      "source": "My Bellingham Now",
      "date": "2026-08-20",
      "excerpt": "Read the full story from My Bellingham Now.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxOc09NRFpLXzVIYUlVZmhJNEh2VFdES2w2ZUdKYThZMGRQSm5ZaUFXb004YUt0ZGQzQUt3dmV0cHNaYmlPXzJHOFoyWTVhY3JWeThxMGQxQTlVMVdKZUw0aHJzWFRmY1BDVW5SUUdxZHM5SXVNYlBMbUtBS2VRTmx2MnFjWEJWUlpaNmNDdzB4dGZyMEo5N3BZRjdTcWpsMVZHcW5jbXM0eHpKY0RFSndMdTBhRG1GQzBXR2Q1ZURiY1lvOUIyZkJ3RQ?oc=5"
    },
    {
      "title": "Ghost Listing: NMSU student loses months of savings to fake apartment listing",
      "source": "KVIA",
      "date": "2026-08-20",
      "excerpt": "Read the full story from KVIA.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTFAySlBrX0Y4YzRfMGNYMS1NQVBOWnhYX3FGT2dCY1ZiRTYtYnBQbTJiMmlyUDUzMVpSLW5kZ3lVUUdBazRLQWtsRzlIcWs3WEtsN2lWWnZubmoyU29QTzBzVC1jQjk3c0Ff?oc=5"
    },
    {
      "title": "LISTEN: WOLVES IN THE THRONE ROOM Go Full Dystopic Black Metal on \"Ghosts Among The Obelisks\"",
      "source": "Metal Injection",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Metal Injection.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxOa1A0LW0xdm9aUHU3U1ptTENmTDZfaHdPS0w5RlpNOFYxcThzQmVBWjNDVE43dlozTEFidGUzdmdZS1dIZGI3VUVRNWVFa1FqU1BUYWhjaElYdnJNVDlvanZuTF9jd0FqdnJaWl9wLTJEVFZpQkk5c21GQjFORlRpdHdjNU5JLVZXWlNyM2ZzNlhXc3pzUlhQdDRlREVBakg2d1lYQ3g4aElKLXpVdm1kTXBtWjZGZWZHeU44Wi13MU5hZFlRSVE?oc=5"
    },
    {
      "title": "Social Security union says it needs $3 billion and another 20,000 workers to fix long wait times and ‘ghost offices’",
      "source": "MarketWatch",
      "date": "2026-08-20",
      "excerpt": "Read the full story from MarketWatch.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMizwFBVV95cUxPT1hlYzZ4aVVtQ2RHZXhVcWM4QWloWGRlUWU5VTVIN3ZFT1lPM09EUHE4V2ZmSDQyM3lrSjc3clMyb0dqNDZJOWNZMlRqb2lLWU9FblBNWVFqY18zSnZiMk43bUd4N3hSNWpPcGpZY0ZPNFhmY0hMb1FIaWc5c2RpeXUtT2loRl9jbFZEaE1pV2xyYkQ4aTVQMFRuOTNFS3RxVHNBU3RwY3dGYVFVdGU2U19Cb0cxRWV6aU5BN3lOcUM1QUlPNDZ5SUNMWVhwU28?oc=5"
    },
    {
      "title": "This Ghost Museum in Maryland is the perfect plan for a beach-town escape to end summer and get into the spirit of the fall season",
      "source": "Secret DC",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Secret DC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiV0FVX3lxTFBOVENVelY4ZFRGTHRGb0pCZGhpaWlEelhmRlNITXlwZmVRUzNfSE9SbGxYMzgwQV9VMUJhU3E5WnpYSnBpamVIYVVWNnAteElxdktDaEp1TQ?oc=5"
    },
    {
      "title": "King Gizzard & The Lizard Wizard Showcase 'Alien Metal' Across 3 Nights At Field Of Vision II",
      "source": "Live For Live Music",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Live For Live Music.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxPZmVZSS02RkVEWkdLSWNpVV9Jb2VYaWhOeVYtb25NRng2QS1ObmRhZ3IwX1AtYkdFV3NYNjRaR3Vjem9MemFWQzVGcDgxY3FQbjRZQ0NGWmdnVEVSWlRQYThoSjBUa0VKRXNGYlZoV0xma0N4eWU1WDM1cDgtRWtHX2ZXcmZmSk9wYXN5cUVUbURfTk9YTnJB?oc=5"
    },
    {
      "title": "FuNkY FrUiT Alien Turtle Mater",
      "source": "Eyewitness News (WEHT/WTVW)",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Eyewitness News (WEHT/WTVW).",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMihgFBVV95cUxQNDdrZGYtSkp5bXFVel9SMWxxNkttX1puMTNvcXBTaDZRendrQmt3V1VPYzhDaU5jV0NEMDNLWXNnby1zeTNHRExMQVlaZmFSOUJGdmI0VDdidjFEazVhUmVaYV85MFhTbUJreWFxeFgwX2lva3ZvM3pyWnY2MnJpZVIzWld1UQ?oc=5"
    },
    {
      "title": "UFO news effect? More say they believe in aliens",
      "source": "Key Biscayne Portal",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Key Biscayne Portal.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxPZVE4YWMtNXpJZk44a2FsYm9OdXlTQ0xsdUNCWjM0NmpkaHlXb2RCOGV1YWozUlFOS2h3Qzlja0pIVjRxNWwwMklPbGFoMUhRM2ROMUFUNng3ZjBKLTAzcTRuVDByODV4djdYMUdvRlgyUldNLW1uTWRmc2FUZnNFZlpGbGlPeFoxYnFXSExPcE05NVlURV9JMVBTc1Vta1BTY1VPV3RlMHZWYW9zN3lLU0dFcWhzNFpST0h2MnlFNGt6UW92WkVrRG1CVWhTdFlhcnAwUmhqZnRGLUFBMUE?oc=5"
    },
    {
      "title": "UFO news effect? More say they believe in aliens",
      "source": "Community Newspaper Group",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Community Newspaper Group.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMihgJBVV95cUxQd1d3Sk1rNDFxcnI1VzFxUDVEQk51akh4QjRTR3NUV0t4Ui1weHk3Z1F5TWxySnpqU2tTTDJKUEhBU1g0RWtHdHBCck4yQktGeFpfZ0xmY2ZNQldXMUl2MWRyOGxEcGpwV0xtUXpOVndkUG9TZkJfMzZJRlBYd1R6cjRrSHhubUg1QXpKLXNHZGVudk1LaVdyX2R6aGVYMU1GaVhmMW4zRExnemw3TlM0TGFPNVo0OFhmendNNEFBWU5Yb3Z4X0k0ME9lYjNBbXJEQkxuQzBHWDZsT0R4ZHNlUV9fVkZ4dmF2SVEwTGZ0OVlQRG5pS3hrTTlvN3pvVVhjRUJPQTF3?oc=5"
    },
    {
      "title": "The world premiere of ‘Geister / Ghost Song’, by Fatih Akin, to open the competitive Official Selection",
      "source": "WebWire",
      "date": "2026-08-20",
      "excerpt": "Read the full story from WebWire.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE9tQUlfZ1k3NFN6d1BMeFhuWGtzQ2NmcFNmSkJIOHo1RVhxVzdPajlnYzNDZUlpcnl4WmFIVS1hRXQ0Y2dKQzdJSmlyRVpUbWpOeGd3TVFWcDJJX29STzJxQg?oc=5"
    },
    {
      "title": "Game preview: Kaukauna Ghosts football vs West Allis Hale",
      "source": "Kaukauna Community News",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Kaukauna Community News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipAFBVV95cUxQM1lMY2k1TE4xdzNyZ3V6QlEzclgzbGcwYWxiam5HSjVhcUtmd2NaUVpjS2JOSWpzQXVXUGlmcXFaMGRybzNKZ1JaMG5SNUowX0wweTZRNEtOZXJhR05wS3d6VEE5cDNoMlhja3BkT3N6ZGJDeGxSSG5qeE8tZzRGeFdNeldwbUZIbGtzOHBMeWdYR1B0elpNT2lVYW5YUFRWT3h2eQ?oc=5"
    },
    {
      "title": "Poll: UFO news coverage is increasing Americans' belief in aliens, especially Gen Z",
      "source": "Talker Research",
      "date": "2026-08-20",
      "excerpt": "Read the full story from Talker Research.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxNdXpFckNHcWZuNFZ6d1lGUXpDMnl6M2xSd2Vkc2tmenhhVlhPdkVLTkVsakJnU3RaelFrQ3dkc3QtYVg4YXZfN2IxbmhKN2gtSFFrOTEyX3ZVeFY3ajhDb3dTODNkX2VSNEcwRG9kOXhSdGY0anhSc29tQXFNdndqdEE2eHBLNk9JMlJ6Q1BNOG0wc0s3eDczTzBKLVhRaGN4bTJNNjhHYUt2eTNs?oc=5"
    },
    {
      "title": "Allison Janney Was Told by an Agent She Could Only Play ‘Aliens and Lesbians’ Because ‘I’m So Tall’",
      "source": "Variety",
      "date": "2026-08-19",
      "excerpt": "Read the full story from Variety.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxOMTEwUWozTkRTUWJkZ3diX0t5TnAwYk1jWTdoS19QZktyaUE1ZjUxTGxqWjlwSFBWbWx3aWJ2VDRtd3B6QVc1RVFWYjNveWpKTWhkcEgxcEs4Z1pRLXFfQjdWMzBXbGZSYzA0ODJ4YUNjRW5XQ25VclpyaXlQZ2RiZEU5S3JLZC0w?oc=5"
    },
    {
      "title": "Perseverance rover watchs alien solar eclipse on Mars photo of the day for Aug. 19, 2026",
      "source": "Space",
      "date": "2026-08-19",
      "excerpt": "Read the full story from Space.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxNUU5oUEdMaTk0bnFyNUpzRnZFcE91c0hZRU1fVFZJR21uN2F6dVgzUkZySVdoVnJFQlRxZ2IwbHJ6VnE5Z2NkWjk5N1RXM21QWXJzOGhXNkpvdldZWjhZcGwwQzNqU3dFTmhmV2xHLTMyQnh1YWV6V25rX0UyQjh2NHk1RjNZLTgxTUt2aktwbWF2eFA3N1FtUDQ0YjFNWnBoLXV3Sm1GTDFJcFM1aEI1c28wUXoxU1BrdWhHall5T3g0blNOVnlvTA?oc=5"
    },
    {
      "title": "Biden-era 'ghost guns' restrictions are unconstitutional, US judge rules",
      "source": "Reuters",
      "date": "2026-08-18",
      "excerpt": "Read the full story from Reuters.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMivwFBVV95cUxPTkprZ3I0ZFpmN01MVkZEVEpqenpfS1BpLVp5d01nbDVyN1NCam1BMWdNUVA3QXpScXVaS0hzajR0RjVodmxqck5EOTQ5U1lhT2ZrdldWQzAwcmtOUGVvY2xpeWF1czZWdjgwUGFIMjFmbmhuTnBDYktpWlpZRmxmQ2NRa2NLSnpfbWtCSFoyNk96QVdQbFBkWm0yclo5MEtLU01JS3FHZXFEcmVhOWluc0lHWnZvRTVFTmlMdWhwZw?oc=5"
    },
    {
      "title": "Feds sitting on 4 types of dead aliens, UFO whistleblower says",
      "source": "NewsNation",
      "date": "2026-08-18",
      "excerpt": "Read the full story from NewsNation.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTFBhRWJTTExYSlp2TkRVT09NS0J6SzJPVTNSY1JiUWNJT2lKRFJsZ3lSR3JqdU5LOWdfR2xwMFRDZm1qT291NGt0QVNfbExlT2IzU2lYOGVfbmY1Yl9MeTBwaEVTSGsteEFJM1JxM0FlZXgxblhiamRmb05pdEhvZ9IBgwFBVV95cUxORWJNcnJaQThjRnNaTk1DS0RJX2hHWnE3emhaMm1WQVJDQUZlYnNuNmExN2U4MW9FWU5GWUZ0T2ltQmtHYVE3U2hlUjl1bjBVNEdiOEd3RFdlbTdpcExIYXNDT3E5M09iWThlUGd4d2pfUGVwVUp4SkRJeThJUU1XZGZfQQ?oc=5"
    },
    {
      "title": "Grief is a Ghost and That Ghost is Your Boyfriend: On C. Russell Price’s “Bisquick: An American Seance”",
      "source": "Chicago Review of Books",
      "date": "2026-08-18",
      "excerpt": "Read the full story from Chicago Review of Books.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxNUll5RkQ2Z1FCU3NyeVVKWnIwU2E1c2otc2ZPQzl1NTJ1cEpxYzlCTFMxX0pTWmhrRHZ4WWRZdUxuS3lXZTJYZWZnWVFwMUFFdXQ0cTQzeFpfSVg1WlZrcG5uVHZfZnlVbDctMk5zUlRNcV9hSElkM1RURG5xenAtOWtQdEFZMkhPcjBLelg2aDV3WXVKQnpKdHliNFhZeHFncWhadzJVZWlyYlpsVENMZ2ROaG5Zdk1hWDJPLVVtTlB3RUR3SklaQWxhQUxPTFRVWmZ3edIB2gFBVV95cUxQNlF0SVNjLVplelFiVzhaaDhLUmFLZUxzbGFDVmd0WEhfakhyQm9NY2l6UDBDcFg3LUxpVHZ5N0lsd2NQNTQ4NDNLRm9lYlk0bC0wNzE5UG80eTNLM1ZmbUhoNVFnUmVpelR5RDFBcDBSRk83OVVvS0M2Nlp3clBCZjB6VGZLSTFodDQwTEdWTHZPZ1daRm1yR0kyTXpXaERnVDhWbnh4Q1Z1TEV3TV9TVFlUQzFFZm1jSjNFNXZtZFZoOHZZYjRBdW90VXBlTXhramxscTl6UjZXUQ?oc=5"
    },
    {
      "title": "10 years of The Ghost Howls",
      "source": "The Ghost Howls",
      "date": "2026-08-15",
      "excerpt": "Read the full story from The Ghost Howls.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE1HUWQyODU4QVpQMXdCdmw1c0JkZVlzNjQ3WGgyVWN2R3dGZ09wODFGOFpCbk5QWW1RQThzUElQdGJ1ci01cVNOUUNqMmFMb1BMWW9pcy1zcjY?oc=5"
    },
    {
      "title": "To Shoot or Not to Shoot a UAP, that is the Question",
      "source": "Avi Loeb – Medium",
      "date": "2026-08-14",
      "excerpt": "Read the full story from Avi Loeb – Medium.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxQMkxEOVFGZ3gzZ1YwbFRnSEJoUlJtc0hZaUdEWjFwR1RYancxRUhJNjk5c21tZURXcXF6dUx5akpiX19McUl2SUxhTGFTdE1mWFFRaVBHVVF6OXRXNWNmSXE3NjYtNDhNaTl6cks3T2x1TGpQb0lmYTEzaXo4Y3QwZzVJcWh4cW5IazA5TWJkN3ZiT3ZteEtz?oc=5"
    },
    {
      "title": "Rocket Lab Unveils GHOST Deployable Launch System to Enable Responsive Space Missions Worldwide",
      "source": "Rocket Lab",
      "date": "2026-08-10",
      "excerpt": "Unveils GHOST Deployable Launch System to Enable Responsive Space Missions Worldwide",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxPeks0el9WNzJZTm9uV1c1VFlkZ1Y4eUdYSnJ0YnRjUy1RT3VacDFIVWV4Z3JxQlRUNUdxdnRMVGhLZ0FzcGd2bXV5N2xQSnpIMzB5T3JSSHItT2l3aXk1VEpvMU9DSGhvRTJTVHNfTTd6aUZfZWJhTjl1TGxNZTRnUW90dEhaVWR1bEpEaUxMUjBUUS1tNVJLU1B3YURFNTgwdEUxTFBjYkpIZmRhUkJ6SXhTT2oyZXh5TEdJanFhTDRlNm5lTk10Um1B?oc=5"
    }
  ]
};
