// AUTO-GENERATED by scripts/update-news.mjs via .github/workflows/update-news.yml
// Do not edit by hand — changes will be overwritten on the next scheduled run.
const newsData = {
  "updatedAt": "2026-08-18T06:48:09.086Z",
  "uk": [
    {
      "title": "Iraq’s ghost villages: Islamic State drove people away – now a new enemy is preventing their return",
      "source": "The Guardian",
      "date": "2026-08-18",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxQN3ZYN2VJS2JPM2tTbjV6Q1NNbWFOZmN6bm9mczNoLWt6WEJoc3gxb3J0N3FoX29wRjZIZnVJWGFiRlY0RmQ3NWpxb2lMdUMxUTRlc1ViemRJak1Ha1hzS2FQLUhWSEc5NE1LRWN0cEd1UUYxZVlwQ0J6YlZpdVZaenF2ZTFrclE2cG1CeHhvVGJyUGkwN2ZmZlJyX0Z1eHpYWHR1RTVuRFJDa1oxbXk0?oc=5"
    },
    {
      "title": "Some of the most promising places to search for alien life aren't planets at all, but moons — because Europa and Enceladus keep oceans liquid beneath their ice partly through the gravitational squeezing of giant planets, an internal heat source that doesn't car",
      "source": "Space Daily",
      "date": "2026-08-18",
      "excerpt": "Read the full story from Space Daily.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTE9mdVBlOHNTRkhTdkYtbEhIWDB1dmFYQjNTUWhfdzFmR1BzY2l5dUJHcjMwNWYzbjFUT2FLTl81NUFUcWltMlNJckpZbFUwRVJyYXF6aTRuMHo1anhsbTJJQWZFb0MxUUxsclN1QzVydFdjekpQNDFtdTJ0TlFVQQ?oc=5"
    },
    {
      "title": "Feds sitting on 4 types of dead aliens, UFO whistleblower says",
      "source": "NewsNation",
      "date": "2026-08-18",
      "excerpt": "Read the full story from NewsNation.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTFBhRWJTTExYSlp2TkRVT09NS0J6SzJPVTNSY1JiUWNJT2lKRFJsZ3lSR3JqdU5LOWdfR2xwMFRDZm1qT291NGt0QVNfbExlT2IzU2lYOGVfbmY1Yl9MeTBwaEVTSGsteEFJM1JxM0FlZXgxblhiamRmb05pdEhvZ9IBgwFBVV95cUxORWJNcnJaQThjRnNaTk1DS0RJX2hHWnE3emhaMm1WQVJDQUZlYnNuNmExN2U4MW9FWU5GWUZ0T2ltQmtHYVE3U2hlUjl1bjBVNEdiOEd3RFdlbTdpcExIYXNDT3E5M09iWThlUGd4d2pfUGVwVUp4SkRJeThJUU1XZGZfQQ?oc=5"
    },
    {
      "title": "New Pentagon UFO files reveal decades of reported sightings in Texas",
      "source": "cbs19.tv",
      "date": "2026-08-18",
      "excerpt": "Read the full story from cbs19.tv.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxNTDdKTFlFQk1IczBYc1VKaHZUb2JFTTNCNHFhSEluX2tqZnN2NEw5QUlhZjlSRzBfRXFNa0djVjNUMnFzWlBVZVpycjhqc01EaFU5QXdnaml5QXpYQ2dtTVVtLWt6MnRucXBfUXU2UFJFOC1DcmVkSW9yTVJRV0N3UHB3OFhxeFN4MzM3X2RKeUdDb1hTZmExM2g0bzZWcHc2dkZKNDgtVXdXdFpha29BRGFhN1dxNzU0aUJaZHFpbzJzTXY5WU1pemZXM3hhV081NWJoTw?oc=5"
    },
    {
      "title": "Kingsmen, Shivas and Alien Boy to Play Music Doc’s Benefit Show",
      "source": "wweek.com",
      "date": "2026-08-18",
      "excerpt": "Read the full story from wweek.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxONmpMSVBLN1hMeVRqTVJsTU5vRWQwT0tSWVBWUld1Q1cwOWp5MnBVNWt0RVRjSERSNml0WGlMZHBRV3FPRjJjUGlpb05tNkxZbmNoemN0a2JJeHNsUXNUTjI4WHdSYkFZajdEZXpucmIzWEtOcTFFYkVPVGJHcmRZbXRRRWtrcnBQVWc1ZUZaeE42VEZMSktiZFM0cnRtZw?oc=5"
    },
    {
      "title": "Ghost Hunters’ Amy Bruni brings haunted cookbook to Portsmouth’s Valley Inn",
      "source": "What's Up Newp",
      "date": "2026-08-17",
      "excerpt": "Read the full story from What's Up Newp.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNMHBVbGRVMGhHY2RmMlQ3NUJzMklsV1lhU21TQTh0VVA5b1JCYnFaM2xUUkllaE5kLWhwMFZKV0NRVTJObnBacF9ON0FnX1VNNk1USTlvNUtyWE8za21IaDBWU05LSml3RllLdkhoampmYVVWaVJKbU1Nb3JUYkd3eEZOWlhRMzZZVGdOTEhDVjZaWVQ0RTJ4VXNTZUg2WU5VY21xQ1J3Yzc4QQ?oc=5"
    },
    {
      "title": "Pentagon releases fifth batch of UAP files",
      "source": "Modern Ghana",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Modern Ghana.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiX0FVX3lxTFBtZmRXcmMzZXItcjdwb3lubjZROTJzNEpwYU9XSlMyQmZXMDdtTDFlM2pMYk1QS1dkUURIYlM5SHRPY0RzRV92elhPMmd4NGFiWVBmOFgtVllfYlc1cEo00gFcQVVfeXFMTkE2TlIyRW5YYXQ4NHVEODZkV2lZM3o2aUxxT09HenNDRWdZU2RxeWFsbUtseExtdENhMENlMEZON1FobTRlUVRYckJXMnhVSWFxdWRyLUVtVFRGMm4?oc=5"
    },
    {
      "title": "Console Archives – UFO: A Day in the Life Review",
      "source": "Cubed3",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Cubed3.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxNYzJFZWUyVEJoRlQzLVI2eDB4RS1mMExNLXRTZEJCT1hMRGpSZUhKN3YyOWpfUS1CZzBfNzRPVWZhNE5aM3duckd2UzRwbnJDelNjYWN4dk15cTRsanBvR3dDd29jMm05ZWZoRVd4VzBjU19JUmZlUkMwUmkzWW5ZWWtPRWJPZUtqdnBOSHdLNEt4TU42TnlfUg?oc=5"
    },
    {
      "title": "The historic structure of Ghost and Lapierre will disappear from the XCO World Cup due to the Accell crisis",
      "source": "Brujulabike.com",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Brujulabike.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxOUnhvT09VckJ6ek1aUDRVd0pSYlYxcmE4bzFmZ0ZRNUxaalRacm5CUnhHbGh6SHpRUXh6cVlQQVB5YVFrSnM1ejE0TUU4MEQzVEVneUZRQ2tlTk1MaEF2aUR5aDA1NVM0V2dEelVkQVJ6WFhWR3RBZ1hsZF9nbXpreGs1bTdLUy1YemJwSHZOd3F4eGs1azJLdWxqdURIdmdzNEhoOHhOR1pvZnh6UGFRUmZmR1pqN1NRMWJQX0xrWVA3alB4VzZkc0xmNTJud1RP?oc=5"
    },
    {
      "title": "Are UAP Orbs Adversary Drones?",
      "source": "Medium",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Medium.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTFBEcThzUnlNN3pwQVFYYjBuaWJvcTNselNQWHBvOXEzRFBrbXg0S1NYT0NKWmxfTk0zcmE1dlgtX1Q3OUtWeWdvZ3pfWDZzUnE1UWdaRHh0Q3N0SnNVWEptaThnTXBrckZUSmVNUTZVNEhKdTFvNmdtQ01R?oc=5"
    },
    {
      "title": "Pentagon releases declassified UFO files from various federal agencies",
      "source": "ABC News - Breaking News, Latest News and Videos",
      "date": "2026-08-17",
      "excerpt": "Read the full story from ABC News - Breaking News, Latest News and Videos.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxQbHVBS3VqSGpNSmgxTWtIa2c3aDI2WE5vS2pfVXRFNjNZd3BlWUdILWh6b245RDMtOXk3Yk91UXktV3k4ckR1dTh1R1lVbFR4MFpLRnhXVmFMMGNsaWs3SXpaTHdzekxQNmRUQkktTHMwTjU3d3V2Z2R4akdIeEM4VGlnNFFzTVVzTXprS1AyT2l3MWdGaDJxUEFiWjBMc3BwMVHSAacBQVVfeXFMUGJvM2xwYk1mVU9OYW1haDlYZlhfaF83ekszcWZrbXRWTzMtZXNOOXNYR1loRThfWElkd3NiVllpX1ZuOGV1eDQ2NHQ5aDR2M1FKZDJmb0Y5TDYzTE53T0lNQ0FvUXQ3QmtYb09QVlRRRGV2eWFjOVJFcUVCVkF1YUlkSkRGclM0eUJVV0VLSl9UZmtBb1ZKUVRtTFhoUUFXWnFiQ1hqSzQ?oc=5"
    },
    {
      "title": "Oldest 'ghost cat' ever recorded caught on camera traps",
      "source": "wamiz.co.uk",
      "date": "2026-08-17",
      "excerpt": "Read the full story from wamiz.co.uk.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiigFBVV95cUxNUXpzOGYyMFY3NmdnOVJoY0tsS3pZY2xxLTgyMlNLRHllMTR2Snp4S3BXSHljQUVoWDFnc1d1WnNkWWJTMWNzUVhUeVA5aGdONmpEWkZ3RUxNRVZQejJyX1dCM013bFQ4M0c2a01FRk1mNTZxYk5GM3A5cGUzOThweGxEX3poZDFTM1E?oc=5"
    },
    {
      "title": "NASA Funds Spherical Flying Robots To Swarm Alien Caves On Saturn's Moon",
      "source": "HotHardware",
      "date": "2026-08-17",
      "excerpt": "Read the full story from HotHardware.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxNOFRPZGxkNUlYLXBaMGhqZzFGTkhKWlBMZUVlUlkyY09aZ2c3aEFLZGpRWm9kSkJfb1lfLUZqZVhUOWxZVGg1RUh3SGpxNjVVSVRDdlJjcTRQNnYxeHIzMWQzelRCbU4zN3o4V2JyZVg1TEFoTWwtTENHV3ZZRC1Kb3dBbDR5a1cyaFUwN0pCNHRlVkdXdzBQR2lSdy1ub2JIQ0E?oc=5"
    },
    {
      "title": "Professor María del Pilar Blanco: Grappling with the ghosts of Caribbean colonialism",
      "source": "University of Oxford",
      "date": "2026-08-17",
      "excerpt": "Read the full story from University of Oxford.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTFA4QUxsVlJIOXZxQkhhdzk0NS1IVzM0S2FxX0x5TkNVRmlNcGFNYm9mbnhKTlo5UmVoS2UxeWdCLTZ1Z1pYYXpEcmhLLWNTT1pJbGxxZkpMUjZ5QW9saDBCMDh2MW9rZHBFMnNxeVNBZHdIQVFoMGYtVUZR?oc=5"
    },
    {
      "title": "On the Trail of Unidentified Anomalous Phenomena – Thoughts of a Disclosure, Data-driven Advocate",
      "source": "Inside Outer Space",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Inside Outer Space.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxOYzlFWXhvVThPTjZ3b3ZOZFRpb1RKZDdiZkptZU54c0NqaEdXOUo1c3RaVjdzbGpObWM3b1JncHFXLXA2cG9nUzY2M01WMjFYOEZhM0xfOEVfMkdxZFBvb0JLdzNVM2thVmJMZ0Z0dTlLTE9iLW90LWtPV3hLMWRrQzFuSnFhSWVuNzVVR2xORlJBbmhyVzF5NWhMM3pYU2pYa1NmaHhRRU9VTEdfYzVXUW0yRUpwQWJ4a3pmOFpJeGltdw?oc=5"
    },
    {
      "title": "This New GHOST Energy Is 100% Liquid Bubblegum",
      "source": "Sporked",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Sporked.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE0zUFBWNWRULV92ZzNTTmNJZENHMGRWd3FTRHJnMU9lUVFKTnVoY2ZFZ3JSUkx2YUNuaVdvZXBSMnE2VGF5NjlUSlVTeEE0MDlKaWpueC1Ua05NNTdEcDh1OFZUTlZPNWV2SmUtcVl6Q0RDSFZPQldZbg?oc=5"
    },
    {
      "title": "The Greek Roswell: UFO Sightings in Greece Nobody Talks About",
      "source": "GreekReporter.com",
      "date": "2026-08-17",
      "excerpt": "Read the full story from GreekReporter.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE85dlVlVjg3QmpTdFJUcXVSQVVVUk9mMjJ1SWNFX2FFQWF1R0haaHB2R2NkMmFFcmpGX0kzOVQ4anpGR0psa3RkREI3VFJXdVB4M3BUbXpJbEZHZ0hqT3V5M0VpbGtuWmM?oc=5"
    },
    {
      "title": "Bigfoot expert explains why a body has never been found",
      "source": "Female First",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Female First.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxQbXZGVklhVDBRNzRvaWZSVFFLYWs0Rl8wM1FHWmlsazA3aklFRTdVVF9uUDVka3g4ZGFuNEZYNHhIeDdiODk0bzh1THRUNkNncVdESHU0TUo3Mi15UnUzMDNIRk0xYkZpMmtIS29LNWRlMUotemJuRTBUYmdWTjR1WDVvZVBVOHhZUDV2WHVTSS1vTkY3MkE?oc=5"
    },
    {
      "title": "Scientists Propose a New Test for Detecting Alien Life Unlike Anything on Earth",
      "source": "The Debrief",
      "date": "2026-08-17",
      "excerpt": "Read the full story from The Debrief.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxOMHRlQmF3MzdxZjNtdDBsTjRYTlhtM016SXJFM2VSZS01ZFJuVG5IVncyQWt4NC1qNFJKc3VabjdNSm1yOGQ0WVFheF9YeGNVbmtkYU50SXdlYmZtNnNOTmZvYXdXTHdwdFMxeVRmTFZNMEZ1V1pKTEF0eHV0SVc4WG0tZjNnZXpVeXF4Y1czQURoT2pNV182SlFVcEo3UUJvQzJ3RG9B?oc=5"
    },
    {
      "title": "Road to FrightFest: Anthony Cousins explains all about cryptid found-footage 'Frogman Returns'",
      "source": "The Hollywood News",
      "date": "2026-08-17",
      "excerpt": "Read the full story from The Hollywood News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxNZ2lzQVZWaUZ1SHQ5N09CSWE4dVNUU05adE9GNmlNMGFSTGJVa3BTVlZCRFlLaTFHdWxkMzVpTldUOTdpVlpONlZkQ2FzTUViUkRSaV94UEdDSWR0YlItMkZJTnVESDJwYU5FY1NiS0pobzJ4ajZRMzl3NllNYzhiNWhiMmZFekxJZHZxNXRhYkI0MnNySXNBVkdUcEhOeFpmc1hmZlQ5Q3YtU19ydTdMWUl3UDV2Vl9vaHhpSUJKbmlaV2tMeUxTeGVzX2g?oc=5"
    },
    {
      "title": "Pilots report ‘unexplained lights’ over Cyprus as EU monitors UFO reports",
      "source": "Cyprus Mail",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Cyprus Mail.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxQQ2NVZkFmZkVqZDhMcVVWSnRyeHh5dEw3b1l6OXhLaFdfaUl0My1CMkpyR0RLRXFHc3R5Q21QY2tiT2Z1VEtvY3pPMXVGN0c3YUNzMnlydnFZTHZ0cGRpQVBLNF85blNpYW1vY1lyOEJUWFR0U3RMSXFYamFnR01DdkVxdlB0cHJrb2o2VVV6ZElEVTI2dGlTdG5rb2k1cG1mUkhjZXc4VENLZw?oc=5"
    },
    {
      "title": "Lanterns review – Kyle Chandler and Aaron Pierre’s alien-hunting superhero caper is a bust",
      "source": "The Guardian",
      "date": "2026-08-17",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxPS19HY0JtSEt4VUFGcU4wVXM5SHFsbjFqN3VEZzBnRjJPSmhVR0I1VDI2RkJhcG0xQnJiNC1Nd1pVZ1pjRVFMdTFiWnpxYzlKeXNVOHRvMmpEYUVOcHNUZHF1WmtKd1g1cDFlTV9TSF84SVpHZ2Ffb3RIZ1BOMjNUWnBkdVVRbkRrZTlmaHpnWnF5NVNqWC0tMjRtWXZEaXpVQjN4VF9SQ2hHdkhtNkZQVHBLR291UnF4NFluYm40TkdUdXR2TmVBY09wb2s1cnNjeTkxNw?oc=5"
    },
    {
      "title": "Will the Pentagon’s Latest UFO Files Satisfy the Alien Theorists?",
      "source": "National Review",
      "date": "2026-08-17",
      "excerpt": "Read the full story from National Review.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxNYWZhN3Ryb0E4SklzNU5KTVlfUGFlU21qR1JqeFlPY2RDSDZvdmNHQTdRZ3NUR3VUMnI2ZVRIRV93RFhkT01ERmdGdHJycFBqR2YwSkZDd0oyeFZDV0IwWmJUTFVNOXJTMl9rVWZPWVlZMVlDOXl3eDUzTTNFYnJuZjFGWXpEbG14Nml6UzdWRkE2bFBIYXJZLWh5TURkNWlsNks4TW5R0gGrAUFVX3lxTE9NWHVxYW1rdmZ1S3VGSFltMm5ka2pLRVlYZEs0cmNIaUptWEFaVzNQV3F4bWV6dTdCbjIzd2lGaE9EdktkZ3NqT2F5TTN5azZpNjVyU1NIVUlNN2N5UEJITXNXT2RPbnIyZGdnazh4bXdXUkp3MndXa0dvZ29Ld2Z1bTdJNFIxMl9zb29WN3ZZekFQM24yVGNwbFpiUW1FMDI4X1R4aUR6M0czdw?oc=5"
    },
    {
      "title": "Johnny and Lillie Flynn announce Beam Cottage with “The Ghost of O’Donahue”",
      "source": "The Line of Best Fit",
      "date": "2026-08-17",
      "excerpt": "Read the full story from The Line of Best Fit.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNUno1VXpoX1VIUHRwa240SWZMX3duN09NTFVPN3pOX0xmRkJTMS1iQ1pGTF8zaktCc0hfNzFfUlB6Q0xnaTZYY2ZKTkd3djZpSHdHZGtqZzVKQlZGdWdubXRibFNPVjc3RFJBTktPYndkNGZRb3FFUDVNX25TTVJvQ0wyckRvNUZJNktlOHRXYXN0Vzc5T3JCLTlpbXRFWjNLNll3SVotaFB2N2VSUUVj?oc=5"
    }
  ],
  "europe": [
    {
      "title": "Pixar's 'Ghost Market' Serving Lunch to Lost Spirits on Oahu",
      "source": "awn.com",
      "date": "2026-08-17",
      "excerpt": "Read the full story from awn.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxQaUNkaEhYX25ibGhGZjhsM2pWUl8ybWtrZlZzRXdEUHA2N3FJYzlsRFpxYlpYaEt5VGwwd1lXcUR4NHN0bXVDSXJIS3N4V3VsaGdXUUE0a3JwR1dMT3BFMTNuZ3U4Z1BCVEtma1hqd3hOSXlVTXljNDd4OWhDWkNybXlB?oc=5"
    },
    {
      "title": "Pampanga ex-mayor, vice mayor face raps over ‘ghost’ project",
      "source": "Inquirer.net",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Inquirer.net.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxObEo2VGYwY29TTGt0aU81c2ZEZ2trekJMSXc2dG8tMk5NZTFPc2JOREpPMDZrc0VHZURoZFRXS0lBRm1lRVVYNmlieGViR0VUQkFPYklMUlVjUGtLS1lHN3c4T3JWc2Z5YU1aeHlBTWtlR3NHRWx4R092cXZNQzJyMjdaN1VVOFhyelhEZFRENS1GckFjazFRZEswMNIBoAFBVV95cUxPRExoODFmSG5YTlBoZUptb1lzTnQ0RzF4S1Z0bHdiTnhhRVFHTkoyVk9hbEEwdzFKbTdSajlPdTBYWWI3dzNwS0I5Vl90YVNBVmNIMktkWGtnQ2pEZVhyUUZQUnN1TzZQMnVQXzQ0SzZpbDBhOGE2ek52djZ4QXlTYmUwVmwtNWxxLWJJVE1PSVNhRXlkdU9QNl9PZGY0QmhU?oc=5"
    },
    {
      "title": "Ghost jobs are real. But the story being told about them isn’t",
      "source": "HR Executive",
      "date": "2026-08-17",
      "excerpt": "Read the full story from HR Executive.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxPckozTmVWZkplMHNFQ2R5NHNQNHJSSUk2U2Q5d3Rmd2ptc3puNFNSQ2t1dWJEQzhiTTZsU0pEUDVHZGlWMDRtWFZRQjBzU2VjTU9rcGo1elZES3JQWHdzbHM1M2VrV1A2ZHBNbHZtUGVVenZkOGdDYTNod0kySFJmUFlMZ1JQSkF4eGp2NXZn?oc=5"
    },
    {
      "title": "244. The End of the Alien Enemies Act Litigation?",
      "source": "One First | Steve Vladeck | Substack",
      "date": "2026-08-17",
      "excerpt": "Read the full story from One First | Steve Vladeck | Substack.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5NRnhuZklMS0lzSExsTUVvZTB6Z3MySUNZWTl2cTZwa0V2TGZaODVZTGVqdXg4X0JuUmtucWVhU0FOWTVEYnBPLXZkcldnNFU4VlFrRUxzcUVYa3ZoMUhraVd3aW5pME1lUkFSSnBLODE?oc=5"
    },
    {
      "title": "'This is unprecedented': Why the Pentagon's recent UFO file releases are so important",
      "source": "Space",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Space.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxPMHRzQ1FOTDZQRjNDU2gteldPUFBxRDBQRVBIbXBaS2hwWEZfYVBQMjVzUVFWR1AxM3V1VGJXRUJvMFo2NzNUWlFrVUplWEpuYU8tQjVDVS05eUpVZFVzR192RFBkT2lnVFJMd2xYdDQ4UmhQdHRzdld4RENZYzgyZ0JySjFseHZ0SWdONlNaYVYwZHJOWU5oM2VYSWlRQ2tGWS16S21UNnhreEtkMzBHakdkU1BJQ29kdkFrLTBYLWlfazJCdWstRkdwQ29acm1iNDJj?oc=5"
    },
    {
      "title": "Ghost In Translation Drone eurorack",
      "source": "synth anatomy",
      "date": "2026-08-17",
      "excerpt": "Read the full story from synth anatomy.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxQV19GRUtabnNlODZBNEZpUGtHT3BZd25BNi1ISnFNVVJuaTNvOTNRU1IyN1Q5SnNIckxFVDVDRTg0ck90bUZtbnpTS1NDNGxxdzEwV0gwYlVrS0JhcG5seVdYejFDdEdIMV9GS2Ffa1hmZGJEelIwbko3TmlaTy1JSm41OXhsTGgwTlBiSWlwekg1cU5Sbml6cVI2d0E4R2R3QVN2djVpd2I4cnNlSUZEQTktblNJX2xfcXZkMGhkYWZtZUtMWFNWVWlveXRRTzhBa29Ga1VhVGM?oc=5"
    },
    {
      "title": "The Ghost of Mitch McConnell Still Runs the Senate",
      "source": "New York Magazine",
      "date": "2026-08-17",
      "excerpt": "Read the full story from New York Magazine.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxQZUdNeEM3V1FiOGVvczF5YkFFM0VIQVg4T2VCNS1lLUtFcVJfRHZmUDRiOW42SmZPT3JzVXl5aWI2LXJuNkFhUmxVYnozdVZOaE9LZlVELS13aVBRYlFKblRPZjM2bmsxN0kxVGZDdjRYbmNBREhJNFFSX3lRVjQzeXM0Ry1oV0R4bVBTcnZDUkxkeFJvYXRuZ2lsZEk?oc=5"
    },
    {
      "title": "US Deports Indian 'Alien' Over \"Sexually Motivated Coercion\" Conviction",
      "source": "NDTV",
      "date": "2026-08-17",
      "excerpt": "Read the full story from NDTV.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxNUEdmYUFEeGR5Ykx4ZnVHNXRCMnVZdVRKSVhEeFpRWUhKbG1yZDJBOVZVcmkwcHBvVmtVaEZfSVNMQWlDdUhGVlpzSElsUW5PVFdUYnBWLTFBV0EtVjRIUUVyZVU1QXp6LXRMZExpbnNhMmlEYno0RUowUGtHWlc5M2VTY0pWZnRGeTF6NTRuZUlrMVd2MmZnbXR6TmZyRTdMMUVBOEd6N3l4UGFvWUFPdHJrQUNvV3ZJODN6Q1JuQ05ZUUHSAcsBQVVfeXFMUERWZ3dBaWlUS0RFVFhXZ0kxQUI2N1NjZmVjbXpQMF9rV1A3YjZ1R2szdVdYUUFHV3VVMkxneGg2cUhHMk9PV1ppcjlKQW1lWUpXZUpBVnlpQU53aWsxZXR0WnpQMUp2M3o1Rmt1QjBQcDB0eVloZk5qN1FHNy1wZFR3V2k0V3Z1aXVZMklETWgyUDNpbHZiWUJ6Q2tTUEkwSnNhTDlVTjdnMERyTW1JLWNDbnhoNkF0amhpQlJ1WmdZZ0kxNFFrUTYxSDQ?oc=5"
    },
    {
      "title": "Exclusive: Brussels keen to monitor UFOs under the radar",
      "source": "Euronews.com",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Euronews.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiowFBVV95cUxPTy1faTB3Z1VFS1oxM3BXQ1pCUFk5YVJBVFRlTmJ3ZUxqRlcwdHZmUkdWOHg3Zk9WVjNvSGNoX1dxMkpuNFk4cDVZcHhhdi1RNW5fWTgzcEJGUHVCVjZpcGppMTVqTFFiR0puckdnYk1jck0zblE2TUhIRmpHcGJaVU1qaWk2R3diVTd0ODlVTDNVblM0dlVsemVQM2xkd25qdndJ?oc=5"
    },
    {
      "title": "Trump’s UFO Files Turn Alien Talk Into Government Business",
      "source": "2oceansvibe News",
      "date": "2026-08-17",
      "excerpt": "Read the full story from 2oceansvibe News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxPalktY1U3LURZUV9saFdJbjZMUTVLLWpSYjFmQWtTeEtmR3J1R2trUV9tTzVTT0lRQ3VYNlRiM3NUaHc3RUZrSU9WcnJwV2k3OWFxX0w1eGx5RVBJZlBSdURuZ1VOcWVvR2cyc1ZSQ3gxTjlSNDBwVWExWmFjR0d6M0UzZlg3Wm5sZVNGbWZvY0FzeVlQckUwLVJpS211WWhKWnEtTXRBZFRHWE9B?oc=5"
    },
    {
      "title": "Alien Metals outlines 12-month programme to advance Georgina copper-gold targets",
      "source": "Yahoo Finance UK",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Yahoo Finance UK.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMihgFBVV95cUxPWVF0MjJyRjhaVW1ESlE0VGxpNGRHeXlCLWZKazRET2dwX2VDTmtXYU11elZqX2RkeFIwMFdaLUtTU0NmdDhxX0ZfMTZqNEwtWFI2LXlFdXNrcUVmcUFyeGM0QmpxM0RsQ2x1czBSMVR0VldVSmx2bGpYLTB6Rm5mZGU3SnZxdw?oc=5"
    },
    {
      "title": "Sicilian Divers Combine Ghost Net Removal With Coral Restoration",
      "source": "Scubaverse",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Scubaverse.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxPcVl4VkFsZ19jTXVIcDBqdDg1QjhER2RIUjJiNXphV3JpZnJSWXUzWVZsckdxWUM0TFE1eWFlNzB4YmM2VFZrLUVJTmtJQ3dfc01falg0ZC1Id0J3ZmxlTloxb3dCT2NpNk10R2RNQUpPeTdvbzBMTDZXamRRYS1YeEVNNld3QWZzRDNva09FVFR4UQ?oc=5"
    },
    {
      "title": "‘Ghost’ win prospects add intrigue to NPB clubs’ jockey for playoff positions",
      "source": "The Japan Times",
      "date": "2026-08-17",
      "excerpt": "Read the full story from The Japan Times.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxPN0pKRGQ4OFBDb1VIR203VHE2YlhOZFBTdjRrTUtuV29wYnVGRXVtZ3pFVnFYSlFIOEd4RnhZU3ZTRG9mR09xU3pyYTNrT18yajlUT3BYNVhMQVYtZFM1NzB4dm1ULTNNS19rNTdxajVkN082QnlEbnVFZzVQaXlhaEJlSXJJZmdIV3EybnRySm5PRVFiVDY4QVhUYTVlSFU?oc=5"
    },
    {
      "title": "Department of War investigating mysterious triangle UFO videos after Post report",
      "source": "nypost.com",
      "date": "2026-08-16",
      "excerpt": "Read the full story from nypost.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxQeE43YWdoX3pDRldDdjBOSkRfQXBHQnRpQ2JQdEpNRzBNRlNyaDE2blNjTW9tSnRYMWFXell0T3FiUUwza05MMWF5NmdtNE5BV1I3Rjg0LWI1dnZvZGJnc2djd1F4Um94dXIyNDhaQ28yRjczbkVIeks2YkQzbjNHVTBiTk9SODN2UFh3WjRBWFlmUVN2LWY4ZXY5SFJfRm5QVDlTTlhtd0VCUzBsSTN0dHBJbW9VY3VfUFR6aXZn?oc=5"
    },
    {
      "title": "Ghost Market will be Pixar's first ghost story, buy people think they've seen its main character before",
      "source": "Creative Bloq",
      "date": "2026-08-15",
      "excerpt": "Read the full story from Creative Bloq.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxQR0pjVnZJNThuQW1fT29PLXI3bS1SZVVPV1l2X2JyLXRveDBreUEySDZIZm5aNER2dEFzN25vQjdfVnRFVDh0bnB6MTdyYWNpNEFXMzY2ZXAtaFAzNWhZbHNQZDF6YUlzQk9zeFMwd1lDSVd1VExlZkd5aTdOcDJzbmxEeTdVR0hOWkZhRXBlUW5XT2FYckEzNTVRNDQtRnlLZndvUFRQMjMzb213MEFnNzQwQXJad0RXMU1tVWNaNWZyd3VCTnhQT3YxYw?oc=5"
    },
    {
      "title": "Late VP Dick Cheney oversaw ‘detainment situation’ of aliens from crashed UFOs: whistleblower",
      "source": "nypost.com",
      "date": "2026-08-15",
      "excerpt": "Read the full story from nypost.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxNR29JeDZNb1ZVTjJ3OFBaWXpPams2TTdSTFpzLW5JUFpFSnlkOUNVNjZUZDBWb0cwOTVELXFrVVE2MWd6M0JxNVR1UjIxdzRPTXpwOWlWeGNxc3RXOFY1QWlmQUpQUlBjT1BZdC1CSWQ2VXZES09oazZveHduS3BYRnRTUmU2cWlLSHc1Y1FrMjRoV2VYazNjRE56QjNOZ1VBdmZyQnhhZXpOcG00MVkwM0hBNENmaEdnMEE?oc=5"
    },
    {
      "title": "10 years of The Ghost Howls",
      "source": "The Ghost Howls",
      "date": "2026-08-15",
      "excerpt": "Read the full story from The Ghost Howls.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE1HUWQyODU4QVpQMXdCdmw1c0JkZVlzNjQ3WGgyVWN2R3dGZ09wODFGOFpCbk5QWW1RQThzUElQdGJ1ci01cVNOUUNqMmFMb1BMWW9pcy1zcjY?oc=5"
    },
    {
      "title": "Edinburgh Festival Fringe 2026 Review: A Ghost Among the Living – Queen Dome, Pleasance Dome",
      "source": "Corr Blimey",
      "date": "2026-08-15",
      "excerpt": "Read the full story from Corr Blimey.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMivwFBVV95cUxNenZacmliV2VaLWd4ZU9CSUd1Wm95am1MMERlVHFkUllwRkhLNDFqLXk4TkMxak84akc4VkYwWnRzeTVyRG95dUprOUpnR1QwWGxDaUdqQlRhLXkwYTUxZDBDeURwbVhrRGZ1RktCMnVGd0dPOGtVc3JOWE5DRWJfbFN3akt3TkxfcHYyYkN6WU9QTnVXUXVqRnhmZGxGejlkZ25KMm9aYlJyc0JBUkx0WE52Y0UzeFRSa0R0TGNkWQ?oc=5"
    },
    {
      "title": "Five Great Reads: life under the Taliban, how to fight back against AI, and … aliens",
      "source": "The Guardian",
      "date": "2026-08-14",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxPSDVrSzA3dGVHaFhzdTA3ZDlscXhwNVE2ZFYwRy1ISW5Cekg3WjdsOXV6bkxuNWM3WFowcFREY1ctZG5KR1VYZEQydl9HLXJ2aDlkbUFCMFlfY1lEdzRSLTFFNVJMaUpIODcwYThGN2tWR05PSDV6SXNNT1FTTTFIbWxXNkNCek43VUxOX3JGMmpZUjVRMEFORXZtazV3bnU2QVdOekpIUmpqRzZMTFZvMjhrLTYyeWN0?oc=5"
    },
    {
      "title": "To Shoot or Not to Shoot a UAP, that is the Question",
      "source": "Medium",
      "date": "2026-08-14",
      "excerpt": "Read the full story from Medium.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxQMkxEOVFGZ3gzZ1YwbFRnSEJoUlJtc0hZaUdEWjFwR1RYancxRUhJNjk5c21tZURXcXF6dUx5akpiX19McUl2SUxhTGFTdE1mWFFRaVBHVVF6OXRXNWNmSXE3NjYtNDhNaTl6cks3T2x1TGpQb0lmYTEzaXo4Y3QwZzVJcWh4cW5IazA5TWJkN3ZiT3ZteEtz?oc=5"
    },
    {
      "title": "Alien: Isolation 2 – another strong female protagonist stalked in a terrifying new world",
      "source": "The Guardian",
      "date": "2026-08-14",
      "excerpt": "Read the full story from The Guardian.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE1JazRZbnJLU3dJOHAxaWhrUjlpcFJIV28yOTJFYV9PcC1NUi00c0hiZkZ6dXlNcjM5cEp6YkR6ZWpTRnU2RFh5NmgwQXN2SF9ocUg5dEFaM3RxYjBNZW5XSUdtU1ZtRmdPd2xRd2dEblQ?oc=5"
    },
    {
      "title": "'Alien Vs. X-Men' Pits Mutantkind Against the Deadliest Species in the Galaxy",
      "source": "Marvel.com",
      "date": "2026-08-13",
      "excerpt": "Read the full story from Marvel.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNdlRNcDRsajB1YnpGaGFmU1luOHZ3X0h6eXdpZi1TUGd1Q0VhX1ZjdDZSaDlOMXc1bXJkNHllOEMxcGdJeGRLeDlaN3g2bXFwSWpSclBTV0ZXZUhHZXAyY3VocHBuUVZlZ1A2YmxFT0F5VFI3c01ubGtkUjdiV1Q5MGFFcmYxcVhJQWxueWFLOEtiaDRHeEZDRkJEdG5KZHJLNXlpRW1nckF6SXM?oc=5"
    },
    {
      "title": "The 17 things you should never do during Hungry Ghost Festival",
      "source": "Time Out Worldwide",
      "date": "2026-08-12",
      "excerpt": "Read the full story from Time Out Worldwide.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipAFBVV95cUxQS0pXa09VR05ZU0RWRUJmQU1mSUpMVUtQdlFfS05kNENsZ0UteHgxRGNReXRGZVhSV21SdWRSVWF5eXpTc0hzTnVtUXlvMVJCTEZxeml1UTJBWTRHa3B5cjNLYzdtX3U0M0Z2M1EtbkFlMmJ1aTlaVGIzaDd6VUE0VDNQa290NWI1YVRsVm8wZ2UwM2hhdklBcGJsT01lRGU5N2JuZg?oc=5"
    },
    {
      "title": "Ghost of Yōtei Complete Edition Comes to PS5 October 1",
      "source": "PlayStation.Blog",
      "date": "2026-08-12",
      "excerpt": "Read the full story from PlayStation.Blog.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQX010bGxvMksyc2h0NzBBV2lfeHB2Y25ONUpRZXFTNlk4V01EWThGcHFtclFNaWdrOWhDaFdxa2hiXzhLVjgxYmlFcHhQdGd6Yy1PWVRJV0Voa2hJMGFyZ3oxWlJwWlhQdHlsX1c1U3E0aGVDM183cGdIMXhWZjF5MEVVbUlaN2g3dlF4VHE5cFdBZU5TNG5vU2gxVQ?oc=5"
    }
  ],
  "us": [
    {
      "title": "Shiba Inu Says Even Ghosts Need a 'Guard Dog,' Then Casually Auditions Its Canine Mascot as the Ultimate",
      "source": "Benzinga",
      "date": "2026-08-18",
      "excerpt": "Read the full story from Benzinga.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipAFBVV95cUxPUDZJV0RHQWZSanpCdkVoS09kTmxBQWN6ZjU5T21RcjE3Ym9rUFF2bUk3SVFQNXBIQTJycHFkUXRjd1l0WUJDeEJMZVFKa3NHdDlJeFg0cGR1bTJhNVpmQmctWXZiT1cyYzQ5VVk4Y1FTcEF4bXJIOEJOelZZWGk0UUwxV3puNkJNSGE4Tlc3RnFJLVFORzBJdkxaUk5NemNheXAyZA?oc=5"
    },
    {
      "title": "Jury selection begins for Albany man accused of printing dozens of ghost guns",
      "source": "NEWS10 ABC",
      "date": "2026-08-18",
      "excerpt": "Read the full story from NEWS10 ABC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxQRVh2SzJ1TWVMQU1FTmZ4Q2hlWmpTWGZFbWMyMHNReV9JLWw4TVNMVE1nZDVyTllfUmNQZ1dIdmVuMkhBUDRnQWozaHlCejJNTEhQY3BOazZfc3B2MnlvMTdDUHF4NlJjMTg4ZTh1TDFobUx3M2h0VXhSVVg3VHFIb0RGemw0UzktUkgwU0dObTU5dE0xaDRBZS1KQUtzeWE3Ni1relItMnAwTU1lZi1WbUl0b1JhUHM?oc=5"
    },
    {
      "title": "WNC Bigfoot Festival in Marion, NC: What to Expect at This Family Day Trip",
      "source": "Kidding Around Greenville",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Kidding Around Greenville.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE1RT2hrcWVkdldVYjBXRm1iWmNYX3RmVElRZm1SQ1JsS0I1TmdXVnRMM0x6WkI1QldaSkxHSVBJeE83VUFkblB5aW94UWNzU2hvRjBCTWdGTi1ScTBGclk5N0RYelNaQ1dtY0dmVWFfamh2bzBRWTBkMA?oc=5"
    },
    {
      "title": "How Zoic brought the terrifying ticks of ‘Alien: Earth’ to life",
      "source": "Reel 360 News",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Reel 360 News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxQLVVacjVXMjZtUUktVUZiQXZpQjhPUnpuM2hNeEVUS0V6aDdiVTQ0MFpxRGlQdUhVRTN1RzBHZWR3MTctRkRXV3pIWnJZU1FCT3FfS201OThYay1HWi1jRUg0RnpkZmYxSGh5a0dvcXRBNmswMXNZR1pFZUt3R3FjeXJsOGxpbWgzQWxUMWNYNUE4Uk0?oc=5"
    },
    {
      "title": "Silver, Ghosts and Clowns in the High Desert of Nevada",
      "source": "MyNorthwest.com",
      "date": "2026-08-17",
      "excerpt": "Read the full story from MyNorthwest.com.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxNczhOQkRxR002dnRpX2ktb28wQnM3NTV1TENjR240N256SkgyQWVyZURVRG1PWUdhdWlOYmJHNjFmODZLbTJyVUZ5NXctUHRzVmdVWWJsLU8yTzhvNk9qQXlWZGN3YnlMYmM4MmRyNHJ6QUcwYTFKdll3NDdpZGlCZmxEblRyamx5UnVSdU1mQ0lsSDljZTdZeEhQYUgwRU44VHctcWJDXzFUWEhpRHltS2trajNPclpW?oc=5"
    },
    {
      "title": "US military bases are ‘ill-equipped’ to stop drone swarms, top commander reveals after Rubio's UAP warning",
      "source": "Fox News",
      "date": "2026-08-17",
      "excerpt": "Read the full story from Fox News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxQV1VFVmM4YUVQdUhlckRtZE5DZC1MSG93VEU2VTR1M211SFQzZXNkaWZfWW5nby1xM1dtV0Y0Q1hFb0VMRU5BWGc0QXB6TXlMT1Z0Z3VqaEdXVFZpaUJpc0Z0UGRQSGJDbHFpb1Y0TFJqY212TzdSY0ZFSlROVGpvRWR1UlYtRTczSkpLajF2QndJckk2Rzg5anVuWXhGZDByb1NZOTJWLUJvaFNwV3NrV2d6VDRONzVjcm4wMTl30gHDAUFVX3lxTE9nSDJwOU9yLVBYdTZzX3VDcU1kMG55ekUxeE1lMGY3UWdEMkpra3VRdXdjdXZGWC00bE5STWgxWFFacGg4OXNWaDNlWF9uY1hOcWxlMkE4SldwMG5VbmM2eXNacFhJeDVsakR0UEtjbTlyYW1SZnJ0NWZ5NTU0Q1ZNSnRka0YxT1J5Si0yTlBfNzdLR09WN0ZjT0JzM1pRcmoxQ3Z3T3BFb2JKWjdjeHJObUFJYXMyUzN2d0t6ajN6S0g2UQ?oc=5"
    },
    {
      "title": "Dem AG candidate Eli Savit: ‘Common sense’ to ban bump stocks, ghost guns",
      "source": "The Manchester Mirror",
      "date": "2026-08-17",
      "excerpt": "Read the full story from The Manchester Mirror.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPdGpuSzNHWlNqQmNFNWpGbEppZ2hzbEhvVUxKUURNU2V4RERRZmhGLVV4NUgtcW9xT0RSYThLVGF2Q2R0UkY3X3l1VG5TWjVncmlyZEZLZU5vblFOTnhWT2tleWlsYkFnajJkWGFHSHU2dDlEODNBZGhDSEJ3Mk5iUTRJRmxnUGdPYS1lWjczN1g5VENKZ2k3NUtneVVGUzZPRVlXalJwM0N2LUZ2T2NpRS1Jbw?oc=5"
    },
    {
      "title": "Former ASU S Myles ‘Ghost’ Rowser enters portal with reported transfer exception",
      "source": "Arizona Sports",
      "date": "2026-08-16",
      "excerpt": "Read the full story from Arizona Sports.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNRGR4SEhaeUhhMHRYcGRRX2Npd2xtblAwSVIxUGhtWXpXbG5rRGVqZGozbEx6S0FHTms4Y0ZKc3ZBMHI1OGlzVURZTE1BbzZCTlJQNFlHdVlXNG9UMzdqWlpYOTNNS2JrMU1QRURXb3JxVnNTSmFxdUZySkJLNGx1WHNCQWswSnRQSDU5MXAxRnN0SzBIX1RUY3B6dlFJZ0tNcDdrOVMybjBIdw?oc=5"
    },
    {
      "title": "Oakland to pay $17 million for death of man during alleged ‘ghost chase,’ attorney says",
      "source": "The Mercury News",
      "date": "2026-08-15",
      "excerpt": "Read the full story from The Mercury News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxQZDFBX3pZWFFoZWhjbnFfNmx0Q2ZTS3dzeWxWOGJQSHBEQjhzelptYU1xLWxKdXFIX2I0dDNwejhxNWxXQWd2ajludkNxT05NSHVBdWxhdEVmVkVNMDVqaE55UVhZejVNMjNvdXdIM2JZakl0ZjJCMkQ3S3l2U0dvRklmbzJsNWV2djFsNnQzUmtBRWVUSVl0T1VkWFVGemgyZDRuek5kRy1xVzc5UHU2dEdDUHRYNnpwMkFUeEZYN1jSAcYBQVVfeXFMTjF4SlM5M1JhUW1tTHJ2WVU1NnJndTRrdE9vbmNodnJXa3ZEZ25fbVZqSlZYWmxpcVJRdzVOUW9pdHR5a0NIRmItckFRdnJ2TXlTSVBpalpBaHo1Qy1TYVlkZmVzdFViZmV0UlFxQmtVeXB0eHFPYlNKNHBsZFpjMkF2TElRSGd3bjduendOYmtwOEpRVktMLXdKV0RTY1Q2aUk4X3Y4SXowcDR3Wm0zNFVxWmU3aThNYmQxb0x2RWx6ZFNRV1B3?oc=5"
    },
    {
      "title": "Texas UFO files have it all: A lockdown, a fake saucer and a glowing egg",
      "source": "San Antonio Express-News",
      "date": "2026-08-15",
      "excerpt": "Read the full story from San Antonio Express-News.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxNTE1UVE1OdktwcEJhSEVvNE91SXJqeHdrelBLVEFBbjU3REw5MnZBdlpBbTRpb3NBb2pFNHVjdEsxT3dxeTBKR0tYLTNRellTc21lTEJEbEdfU21OTjE5cmRIc3Fwd1l0a1pMRnRMWWhpVWgtbjdYb0Q5dGVUOFlpOG5lb2FrMzdfTEFTN0pkLUFTTTZ3VjNv?oc=5"
    },
    {
      "title": "31 People Confess The Unexplainable Paranormal Moments They've Experienced That Haunt Them",
      "source": "BuzzFeed",
      "date": "2026-08-13",
      "excerpt": "Read the full story from BuzzFeed.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxNWlE5cE1TaUtwbHRKc3NYME1ERXJQQW1hU3lKdjlOTlRPZjZ5R2JZM2JpRlVMNmpPTTN5OXBhLUxLejZYM25Kdnkzc1NLQlJ4WVRPMmtpTUtvU1hEVl9ZR2R1Ukh0ZmtEbDdsdTMtWTZld2FIT2VmSWJwWDE3WGdFNnN5NkNLamRGd2hsRzBRckZSSDk2SE5ubHV4Uy1FQUE?oc=5"
    },
    {
      "title": "The Freaky, Tentacled ‘Alien’ Bait Turning American Fishing Upside Down",
      "source": "WSJ",
      "date": "2026-08-12",
      "excerpt": "Read the full story from WSJ.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxONEgyZjJZcFF2c3dJOTBFRC1Ub05XUUhwT0k1SEpub3h4X0NiZEllbzI4UFEzaS0yblVBZ3RnRUFHcklGeTdqdDJEcmNmcXpHbWh1eVptVkJJSkR2ellHaWxZbmVUczg0QjhoaS1iSVRvZTFNeHJsZURnOEI5TFFWaFBkVDEyOVMzeDNzTmZPZXh0N01ydHNvUlZaWWc1NkxUZzJValhKOA?oc=5"
    },
    {
      "title": "Ghosts Behind Glass: Encountering Extinction in Museums by Dolly Jørgensen",
      "source": "California Review of Books",
      "date": "2026-08-11",
      "excerpt": "Read the full story from California Review of Books.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxQaDAzSUpkbFBUdGh3SUdCMHhBSndNdVNDMjVPUXFySnN4VFR1UEtIZnJ6NjJMT091VXRJOGFvOFp0M21IRnM1Rlo0dWJmemlIZmZUMkl5ek9MWFdQS2dQNDI2c1pOamFYdjZWV3N0QzVTQ0JiRDFxQ2ZmZlhFLUZnMlYwNlByWER4UjR1R2hBWmhrMzVBWkZLRQ?oc=5"
    },
    {
      "title": "In the Ruins of Wyoming's Ghost Towns, Novelist Téa Obreht Plays House With the Dead",
      "source": "Condé Nast Traveler",
      "date": "2026-08-11",
      "excerpt": "Read the full story from Condé Nast Traveler.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxOeTVCZUc1azJXWEtDQUM0SUdvNURkOGh3VHhpM1ZBb1ctMW5YaWtnQmdwVWpsM193XzNTT3Q0QUxYUUprY3Q5R1MtY2VRM2I1Tkt4NHYwTHVFV0ZsUTBTRm1hVVF0NkgzNUJuUjgwOV9JVFc4blQtN2h4Q0xYLXZydnZmLUxLeG8wQUJOc1BvSUE4OE1RQ1BWVGc4UWozaWVVeUZUZTJScm1tczJPTXN1V3VEN1hpZw?oc=5"
    },
    {
      "title": "What Does Downing of UAP Imply About Their Nature?",
      "source": "Medium",
      "date": "2026-08-11",
      "excerpt": "Read the full story from Medium.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxOTmF0QTAxZXBkdzFXMVFzc29YRDFHcnRaOVFjd0hiaUh2MmxRWmtuV1NoUzVkYWxXTDNHVTd0NkZXZE1sMi13cVF5SDhvUEw3dmJJYzVZTnVnSlZ3a1RYNmdEdDEtTV91Y2JTZ0FqbEduUkdvMmxhelhoRTJKOWZxUnBHRlBta0doV3JiLWtlTXdBd1ljVEpkYndxdw?oc=5"
    },
    {
      "title": "Rocket Lab Unveils GHOST Deployable Launch System to Enable Responsive Space Missions Worldwide",
      "source": "Rocket Lab",
      "date": "2026-08-10",
      "excerpt": "Unveils GHOST Deployable Launch System to Enable Responsive Space Missions Worldwide",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxPeks0el9WNzJZTm9uV1c1VFlkZ1Y4eUdYSnJ0YnRjUy1RT3VacDFIVWV4Z3JxQlRUNUdxdnRMVGhLZ0FzcGd2bXV5N2xQSnpIMzB5T3JSSHItT2l3aXk1VEpvMU9DSGhvRTJTVHNfTTd6aUZfZWJhTjl1TGxNZTRnUW90dEhaVWR1bEpEaUxMUjBUUS1tNVJLU1B3YURFNTgwdEUxTFBjYkpIZmRhUkJ6SXhTT2oyZXh5TEdJanFhTDRlNm5lTk10Um1B?oc=5"
    },
    {
      "title": "Is There a UFO Base on the Moon?",
      "source": "Medium",
      "date": "2026-08-07",
      "excerpt": "Read the full story from Medium.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMifEFVX3lxTE9oLVh0YWlPd2pZUWxVd3kxMFExQmxzaGVlUWJFQ05YSUdMWnRYUFE1czNueXBPZG9aRUNiQy04NDc4QmowcFlvRDJwS0Rub29SNkdPTnBfLVZwTXhsVTMtd2pYQXZPaXIxVXAxUy1aT1pNS3hTUnI2ekZyOFg?oc=5"
    },
    {
      "title": "Department of War Publishes Fifth Release of Unidentified Anomalous Phenomena Files on WAR.GOV/UFO",
      "source": "U.S. Department of War (.gov)",
      "date": "2026-08-07",
      "excerpt": "Read the full story from U.S. Department of War (.gov).",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxNaHJtX1ZyZFY5aXFyd29oeDBjY2xxbTVuaW4xeDU3cjZ3Ml9rY1c1cE5zQXJ2RFE0YTR6NjZRRHo1SmhCUHpFSUsxVG9zRlJzNUZpZGpFd0lMOExjUjJWN0E5OTYwa09XbVpaRHMyZXNLaWpad3VpMndsc2taVjdvTzVaX21kcG1ENHJvcnlJQXNmdXZWMTBmQkkxYk4tU2VpcWVuTDZ6eUFEOWdOUEU1N2kxRE90NEF0VlFCOHc0UkJoTTdfQ1JNbDNVUTUyemlvcHd4MA?oc=5"
    },
    {
      "title": "Pentagon releases fresh batch of UFO files",
      "source": "BBC",
      "date": "2026-08-07",
      "excerpt": "Read the full story from BBC.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTFBGNjdZaXNSbFNGN1dHdk1tQkx0aXo5V0VEczJYSWxvT0ZQY2ZsRGdHZFU3dDhvekpnV1pPNlVIZWlWQ0RfVHN4aUh3a3V1SlEybFE0bHI1SXpJUQ?oc=5"
    },
    {
      "title": "Presidential Unsealing and Reporting System for UAP Encounters (PURSUE)",
      "source": "U.S. Department of War (.gov)",
      "date": "2026-08-04",
      "excerpt": "Read the full story from U.S. Department of War (.gov).",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE14VzNpMEZ3V21pVnY0aG9wWXl4Zk1jSmlzOVExVFlPcHRvb0NwWm9IZmJSTVZUS1NwdDBtaUxvdTRoMzJPT1JtaV9QZDUzOV8taEJnc0JKR0szSDA?oc=5"
    },
    {
      "title": "Do Some UAP Represent Earth-Based-Tech of a Pre-Human Origin?",
      "source": "Medium",
      "date": "2026-07-24",
      "excerpt": "Read the full story from Medium.",
      "image": null,
      "url": "https://news.google.com/rss/articles/CBMiowFBVV95cUxPdG1DRXBGTy1ZbWR6RUFPUGxWQ0xMMm50MUFsMG5hOVZYQkkzWWtvdU5qc09tcVFuWGlSaHB3SC1iVnd0c0Y2WEpGTWdmc2NvYVVwbWZpS21ueElVN1pOTHFxdGpyR3QzM0l0YUFOYTZoZFZqOWpkcHR2R0dLU1lIY2lXeHpGbHdMTGtOYnU3Z2ZxWmR1UWV0SjlwU2dSaTFjS0dB?oc=5"
    }
  ]
};
