// AUTO-GENERATED by scripts/update-satellites.mjs via .github/workflows/update-news.yml
// Do not edit by hand — changes will be overwritten on the next scheduled run.
const satelliteData = {
  "updatedAt": "2026-09-10T16:07:39.960Z",
  "iss": [],
  "visual": [],
  "starlink": [],
  "starlinkSampleOf": 0
};
