// AUTO-GENERATED by scripts/update-satellites.mjs via .github/workflows/update-news.yml
// Do not edit by hand — changes will be overwritten on the next scheduled run.
const satelliteData = {
  "updatedAt": "2026-10-02T04:44:18.195Z",
  "iss": [],
  "visual": [],
  "starlink": [],
  "starlinkSampleOf": 0
};
