// Fetches regional RSS feeds, filters for UFO/paranormal-related keywords,
// and writes the result to js/news-data.js. Run via .github/workflows/update-news.yml.
import Parser from "rss-parser";
import { writeFile } from "node:fs/promises";

const parser = new Parser({
  customFields: {
    item: [
      ["media:thumbnail", "mediaThumbnail"],
      ["media:content", "mediaContent"],
    ],
  },
});

const FEEDS = {
  uk: [
    { url: "https://feeds.bbci.co.uk/news/uk/rss.xml", name: "BBC News" },
    { url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", name: "BBC Science & Environment" },
  ],
  europe: [
    { url: "https://www.euronews.com/rss", name: "Euronews" },
    { url: "https://www.esa.int/rssfeed/TopNews", name: "European Space Agency" },
  ],
  us: [
    { url: "https://feeds.npr.org/1001/rss.xml", name: "NPR News" },
    { url: "https://www.nasa.gov/rss/dyn/breaking_news.rss", name: "NASA" },
  ],
};

const KEYWORD_PATTERN = new RegExp(
  "\\b(ufos?|uaps?|aliens?|extraterrestrial|paranormal|ghosts?|haunt(ed|ing)?|cryptids?|bigfoot|" +
  "unidentified (anomalous|aerial|flying) (phenomena|object)s?)\\b",
  "i"
);

const MAX_ITEMS_PER_REGION = 15;
const REQUEST_HEADERS = { "User-Agent": "Mozilla/5.0 ParalnoiaNewsBot/1.0 (+https://github.com/jimrbrodie/Building_Paralnoia)" };

function stripHtml(html) {
  return (html || "").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
}

function truncate(text, max) {
  if (text.length <= max) return text;
  return text.slice(0, max).replace(/\s+\S*$/, "") + "…";
}

function extractImage(item) {
  if (item.mediaThumbnail?.$?.url) return item.mediaThumbnail.$.url;
  if (item.mediaContent?.$?.url) return item.mediaContent.$.url;
  if (item.enclosure?.url) return item.enclosure.url;
  const match = /<img[^>]+src="([^"]+)"/i.exec(item.content || item["content:encoded"] || "");
  return match ? match[1] : null;
}

async function fetchFeed(feed) {
  try {
    const res = await fetch(feed.url, { headers: REQUEST_HEADERS });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const xml = await res.text();
    const parsed = await parser.parseString(xml);
    return (parsed.items || []).map((item) => ({ ...item, sourceName: feed.name }));
  } catch (err) {
    console.error(`Failed to fetch ${feed.name} (${feed.url}): ${err.message}`);
    return [];
  }
}

async function buildRegion(region, feeds) {
  const results = await Promise.all(feeds.map(fetchFeed));
  const allItems = results.flat();

  const seen = new Set();
  const matched = [];

  for (const item of allItems) {
    const title = item.title || "";
    const snippet = item.contentSnippet || stripHtml(item.content || item["content:encoded"] || "");
    const haystack = `${title} ${snippet}`;

    if (!KEYWORD_PATTERN.test(haystack)) continue;
    if (!item.link || seen.has(item.link)) continue;
    seen.add(item.link);

    matched.push({
      title: title.trim(),
      source: item.sourceName,
      date: item.isoDate ? item.isoDate.slice(0, 10) : new Date().toISOString().slice(0, 10),
      excerpt: truncate(snippet, 160),
      image: extractImage(item),
      url: item.link,
      _sortDate: item.isoDate ? new Date(item.isoDate).getTime() : 0,
    });
  }

  matched.sort((a, b) => b._sortDate - a._sortDate);
  return matched.slice(0, MAX_ITEMS_PER_REGION).map(({ _sortDate, ...rest }) => rest);
}

async function main() {
  const [uk, europe, us] = await Promise.all([
    buildRegion("uk", FEEDS.uk),
    buildRegion("europe", FEEDS.europe),
    buildRegion("us", FEEDS.us),
  ]);

  const newsData = {
    updatedAt: new Date().toISOString(),
    uk,
    europe,
    us,
  };

  const fileContents = `// AUTO-GENERATED by scripts/update-news.mjs via .github/workflows/update-news.yml
// Do not edit by hand — changes will be overwritten on the next scheduled run.
const newsData = ${JSON.stringify(newsData, null, 2)};
`;

  await writeFile(new URL("../js/news-data.js", import.meta.url), fileContents, "utf-8");
  console.log(`Wrote ${uk.length} UK, ${europe.length} European, ${us.length} US items.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
